package main

import (
  "bytes"
  "database/sql"
  "encoding/json"
  "fmt"
  "log"
  "net/http"
  "net/http/httptest"
  "net/url"
  "os"
  "path/filepath"
  "strings"
  "time"

  dbpkg "github.com/you/pos-backend/db"
  "github.com/you/pos-backend/handlers"
)

func parseEnvFile(path string) (map[string]string, error) { out:=map[string]string{}; data,err:=os.ReadFile(path); if err!=nil{return nil,err}; for _,line:= range strings.Split(string(data),"\n"){ line=strings.TrimSpace(line); if line==""||strings.HasPrefix(line,"#"){continue}; p:=strings.SplitN(line,"=",2); if len(p)==2 { out[strings.TrimSpace(p[0])] = strings.TrimSpace(p[1]) } }; return out,nil }
func withTunnelPort(dsn string, port string) string { if strings.TrimSpace(dsn)==""||strings.TrimSpace(port)==""{return dsn}; parsed,err:=url.Parse(dsn); if err!=nil{return dsn}; host:=parsed.Hostname(); if host==""{return dsn}; parsed.Host=host+":"+port; return parsed.String() }
func openDB(dsn string) (*sql.DB, error) { db,err:=sql.Open(dbpkg.PostgresCompatDriverName(), dsn); if err!=nil{return nil,err}; if err:=db.Ping(); err!=nil{return nil,err}; if err:=dbpkg.EnsurePostgresRuntimeCompat(db); err!=nil{return nil,err}; return db,nil }
func doJSON(handler http.HandlerFunc, method, target string, payload any, headers map[string]string) (int, map[string]any, http.Header, string) { var body bytes.Buffer; if payload!=nil { _ = json.NewEncoder(&body).Encode(payload) }; req:=httptest.NewRequest(method,target,&body); if payload!=nil { req.Header.Set("Content-Type","application/json") }; for k,v:= range headers { req.Header.Set(k,v) }; rr:=httptest.NewRecorder(); handler(rr,req); res:=rr.Result(); defer res.Body.Close(); raw:=rr.Body.String(); parsed:=map[string]any{}; _ = json.Unmarshal([]byte(raw), &parsed); return res.StatusCode, parsed, res.Header, raw }
func mustStatus(label string, status int, allowed ...int) { for _,v:= range allowed { if status==v { return } }; log.Fatalf("%s status inesperado: %d, esperados=%v", label, status, allowed) }
func main(){ _ = os.Setenv("RECAPTCHA_DEV_BYPASS", "1"); envs,err:=parseEnvFile(filepath.Join(".env.local")); if err!=nil{log.Fatal(err)}; empDSN:=envs["DB_EMPRESAS_DSN"]; superDSN:=envs["DB_SUPERADMIN_DSN"]; if envs["DB_VPS_TUNNEL_ENABLED"]=="1" { port:=strings.TrimSpace(envs["DB_VPS_LOCAL_PORT"]); empDSN=withTunnelPort(empDSN,port); superDSN=withTunnelPort(superDSN,port) }; dbEmp,err:=openDB(empDSN); if err!=nil{log.Fatal(err)}; defer dbEmp.Close(); dbSuper,err:=openDB(superDSN); if err!=nil{log.Fatal(err)}; defer dbSuper.Close();
const empresaID=7; const cashierEmail="cajero.calipso@powerfulcontrolsystem.local"; const cashierPassword="CalipsoCaja2026!"; const adminEmail="powerfulcontrolsystem@gmail.com"; stamp:=time.Now().Format("20060102-150405");
loginHandler:=handlers.WithEmpresaPublicScope(handlers.EmpresaUsuarioLoginHandler(dbEmp, dbSuper)); st,loginBody,loginHeaders,raw:=doJSON(loginHandler,http.MethodPost,fmt.Sprintf("/api/empresa/usuarios/login?empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"email":cashierEmail,"password":cashierPassword},nil); mustStatus("login",st,http.StatusOK); if loginBody["ok"]!=true { log.Fatalf("login no exitoso: %s",raw) }; cookies:=loginHeaders.Values("Set-Cookie"); if len(cookies)==0 { log.Fatalf("login sin cookie: %s",raw) }
permsHandler:=handlers.WithEmpresaSeguridadPermissions(dbEmp, dbSuper, handlers.EmpresaPermisosContextoHandler(dbSuper)); st,permsBody,_,raw:=doJSON(permsHandler,http.MethodGet,fmt.Sprintf("/api/empresa/permisos_contexto?empresa_id=%d",empresaID),nil,map[string]string{"X-Admin-Email":cashierEmail}); mustStatus("permisos",st,http.StatusOK); pages,_:=permsBody["paginas"].(map[string]any); stationsAllowed:=false; panelAllowed:=true; crmAllowed:=true; if pages!=nil { if v,ok:=pages["linkEstaciones"].(bool);ok{stationsAllowed=v}; if v,ok:=pages["linkPanelEmpresa"].(bool);ok{panelAllowed=v}; if v,ok:=pages["linkCRMComercial"].(bool);ok{crmAllowed=v} }; if !stationsAllowed || panelAllowed || crmAllowed { log.Fatalf("permisos de cajero inesperados: %s",raw) }
hdrAdmin:=map[string]string{"X-Admin-Email":adminEmail}; leadsHandler:=handlers.WithEmpresaClientesPermissions(dbEmp, dbSuper, handlers.EmpresaCRMLeadsHandler(dbEmp)); interHandler:=handlers.WithEmpresaClientesPermissions(dbEmp, dbSuper, handlers.EmpresaCRMInteraccionesHandler(dbEmp)); campHandler:=handlers.WithEmpresaClientesPermissions(dbEmp, dbSuper, handlers.EmpresaCRMCampanasHandler(dbEmp)); cotHandler:=handlers.WithEmpresaVentasPermissions(dbEmp, dbSuper, handlers.EmpresaVentasCotizacionesHandler(dbEmp));
st,leadBody,_,raw:=doJSON(leadsHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/leads?empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"nombre":"Lead QA CRM "+stamp,"empresa_origen":"Motel Calipso QA","email":"lead."+stamp+"@example.com","telefono":"3000000000","canal_origen":"web","valor_potencial":250000,"probabilidad":55,"propietario":"Equipo CRM","notas":"Prueba automatizada CRM"},hdrAdmin); mustStatus("lead_create",st,http.StatusCreated); leadID:=int64(leadBody["id"].(float64));
st,_,_,raw=doJSON(leadsHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/leads?action=transicionar&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":leadID,"nuevo_estado":"contactado","estado_lead":"contactado"},hdrAdmin); mustStatus("lead_transition",st,http.StatusOK);
st,interBody,_,raw:=doJSON(interHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/interacciones?empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"lead_id":leadID,"tipo_interaccion":"seguimiento","fecha_interaccion":time.Now().Format("2006-01-02 15:04:05"),"resumen":"Llamada inicial CRM "+stamp,"resultado":"Cliente interesado","usuario_responsable":"Equipo CRM","proxima_accion":"Enviar cotizacion","estado_interaccion":"abierta"},hdrAdmin); mustStatus("inter_create",st,http.StatusCreated); interID:=int64(interBody["id"].(float64));
st,_,_,raw=doJSON(interHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/interacciones?action=transicionar&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":interID,"nuevo_estado":"en_progreso","estado_interaccion":"en_progreso"},hdrAdmin); mustStatus("inter_transition",st,http.StatusOK);
st,campBody,_,raw:=doJSON(campHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/campanas?empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"nombre":"Campana QA CRM "+stamp,"canal":"whatsapp","objetivo":"Prueba de modulo CRM","presupuesto":120000,"fecha_inicio":time.Now().Format("2006-01-02"),"fecha_fin":time.Now().AddDate(0,0,7).Format("2006-01-02"),"estado_campana":"planificada","audiencia":"clientes frecuentes","kpi_objetivo":"conversion"},hdrAdmin); mustStatus("campana_create",st,http.StatusCreated); campID:=int64(campBody["id"].(float64));
st,_,_,raw=doJSON(campHandler,http.MethodPost,fmt.Sprintf("/api/empresa/crm/campanas?action=transicionar&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":campID,"nuevo_estado":"activa","estado_campana":"activa"},hdrAdmin); mustStatus("campana_transition",st,http.StatusOK);
st,cotBody,_,raw:=doJSON(cotHandler,http.MethodPost,fmt.Sprintf("/api/empresa/ventas/cotizaciones?empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"cliente_nombre":"Lead QA CRM "+stamp,"fecha_documento":time.Now().Format("2006-01-02"),"vigencia_hasta":time.Now().AddDate(0,0,10).Format("2006-01-02"),"estado_documento":"borrador","subtotal":100000,"descuento_total":0,"impuesto_total":19000,"total":119000,"moneda":"COP","origen":fmt.Sprintf("lead-%d",leadID),"notas":"Cotizacion de prueba CRM"},hdrAdmin); mustStatus("cotizacion_create",st,http.StatusCreated); cotID:=int64(cotBody["id"].(float64));
for _,state:= range []string{"emitida","aprobada"} { st,_,_,raw=doJSON(cotHandler,http.MethodPost,fmt.Sprintf("/api/empresa/ventas/cotizaciones?action=transicionar&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":cotID,"nuevo_estado":state,"estado_documento":state},hdrAdmin); mustStatus("cotizacion_transition_"+state,st,http.StatusOK) }
st,pedidoBody,_,raw:=doJSON(cotHandler,http.MethodPost,fmt.Sprintf("/api/empresa/ventas/cotizaciones?action=convertir_pedido&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":cotID},hdrAdmin); mustStatus("cotizacion_to_pedido",st,http.StatusOK); pedidoID:=int64(0); if v,ok:=pedidoBody["pedido_id"].(float64);ok{pedidoID=int64(v)};
st,docBody,_,raw:=doJSON(cotHandler,http.MethodPost,fmt.Sprintf("/api/empresa/ventas/cotizaciones?action=convertir_documento_final&empresa_id=%d",empresaID),map[string]any{"empresa_id":empresaID,"id":cotID},hdrAdmin); mustStatus("cotizacion_to_documento",st,http.StatusOK); docCreated,_:=docBody["documento_final_creado"].(bool);
st,embudoBody,_,raw:=doJSON(cotHandler,http.MethodGet,fmt.Sprintf("/api/empresa/ventas/cotizaciones?action=embudo&empresa_id=%d&limit=10",empresaID),nil,hdrAdmin); mustStatus("embudo",st,http.StatusOK); if _,ok:=embudoBody["summary"].(map[string]any);!ok{ log.Fatalf("embudo sin summary valido: %s",raw) };
fmt.Printf("login_cashier=OK cookie_set=%t only_estaciones=%t role=%v\n",len(cookies)>0,stationsAllowed && !panelAllowed && !crmAllowed,loginBody["rol"]); fmt.Printf("crm_smoke=OK lead_id=%d interaccion_id=%d campana_id=%d cotizacion_id=%d pedido_id=%d documento_final=%t\n",leadID,interID,campID,cotID,pedidoID,docCreated)
}
