(function(){
  "use strict";
  function q(k){return new URLSearchParams(location.search).get(k)||""}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function n(v){var x=Number(v);return Number.isFinite(x)?x:0}
  function money(v){return "$"+Number(v||0).toLocaleString("es-CO")}
  async function api(action,opts){var url="/api/empresa/domicilios?empresa_id="+encodeURIComponent(empresaId)+(action?"&action="+action:"");var res=await fetch(url,Object.assign({credentials:"same-origin"},opts||{}));var txt=await res.text();var data={};try{data=txt?JSON.parse(txt):{}}catch(_){data={raw:txt}}if(!res.ok)throw new Error(data.error||data.raw||txt||("HTTP "+res.status));return data}
  function post(action,payload,method){return api(action,{method:method||"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload||{})})}
  var empresaId=q("empresa_id")||(window.__resolveEmpresaIdContext?window.__resolveEmpresaIdContext():"");
  var state={restaurants:[],couriers:[],menu:[],orders:[],offers:[],cfg:null,integracionNucleo:null};
  var map=L.map("domMap").setView([4.711,-74.0721],12);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap"}).addTo(map);
  var layer=L.layerGroup().addTo(map);
  var tabMeta={
    resumen:["Resumen operativo","Lee cola, cobertura, aliados y accesos de delivery en un solo panel."],
    central:["Central de pedidos","Monitorea pedidos, despacho y ubicacion de domiciliarios en tiempo real."],
    restaurantes:["Restaurantes","Administra aliados, acceso y tiempos de preparacion."],
    domiciliarios:["Domiciliarios","Registra flota, PIN movil y disponibilidad."],
    menu:["Menu","Publica productos por restaurante para el portal cliente."],
    config:["Configuracion","Define tarifas, radios, comisiones y seguridad."]
  };

  function msg(text,bad){var el=document.getElementById("domMsg");el.textContent=text||"";el.classList.toggle("is-error",!!bad)}
  function renderCoreIntegration(){
    var el=document.getElementById("domCoreSummary");if(!el)return;
    var r=state.integracionNucleo;
    if(!r){el.textContent="Nucleo: pedidos entregados generan clientes, servicios, ventas y pagos centrales.";return}
    var errs=(r.errores||[]).length;
    el.textContent="Nucleo: "+(r.pedidos_sincronizados||0)+" pedidos, "+(r.menu_servicios_sincronizados||0)+" servicios de menu y "+(r.clientes_sincronizados||0)+" clientes sincronizados"+(errs?" ("+errs+" observaciones).":".");
  }
  function setTab(tab){
    if(!tabMeta[tab])tab="resumen";
    document.querySelectorAll("[data-tab]").forEach(function(b){b.classList.toggle("is-active",b.dataset.tab===tab)});
    document.querySelectorAll(".dom-panel").forEach(function(p){p.hidden=p.id!=="panel-"+tab});
    var titles={central:["Central","Monitorea pedidos y ubicación de domiciliarios en tiempo real."],restaurantes:["Restaurantes","Administra aliados, acceso y tiempos de preparación."],domiciliarios:["Domiciliarios","Registra flota, PIN móvil y disponibilidad."],menu:["Menú","Publica productos por restaurante para el portal cliente."],config:["Configuración","Define tarifas, radios, comisiones y seguridad."]};
    document.getElementById("sectionTitle").textContent=tabMeta[tab][0];document.getElementById("sectionSummary").textContent=tabMeta[tab][1];
    try{var next=new URL(window.location.href);next.searchParams.set("tab",tab);window.history.replaceState({},"",next.toString())}catch(_){}
    if(tab==="central")setTimeout(function(){map.invalidateSize();drawMap()},80);
  }
  function initialTabFromURL(){var tab=q("tab")||q("view")||q("section");return tabMeta[tab]?tab:"resumen"}
  function fillConfig(c){state.cfg=c||{};document.getElementById("cfgNombreSistema").value=state.cfg.nombre_sistema||"Domicilios";document.getElementById("cfgNombrePortal").value=state.cfg.nombre_portal||"Pide a domicilio";document.getElementById("cfgMoneda").value=state.cfg.moneda||"COP";document.getElementById("cfgCobertura").value=state.cfg.radio_cobertura_km||8;document.getElementById("cfgAsignacion").value=state.cfg.radio_asignacion_km||6;document.getElementById("cfgRonda").value=state.cfg.domiciliarios_por_ronda||5;document.getElementById("cfgTarifaBase").value=state.cfg.tarifa_base||0;document.getElementById("cfgTarifaKm").value=state.cfg.tarifa_km||0;document.getElementById("cfgComision").value=state.cfg.comision_porcentaje||0;document.getElementById("cfgAuto").checked=!!state.cfg.auto_asignar;document.getElementById("cfgPublico").checked=!!state.cfg.permitir_pedidos_publicos;document.getElementById("cfgCodigo").checked=!!state.cfg.exigir_codigo_entrega}
  function fillKpis(d){var pendientes=d.pedidos_pendientes||0,preparacion=d.pedidos_preparacion||0,ruta=d.pedidos_ruta||0,disponibles=d.domiciliarios_disponibles||0;document.getElementById("kpiPendientes").textContent=pendientes;document.getElementById("kpiPreparacion").textContent=preparacion;document.getElementById("kpiRuta").textContent=ruta;document.getElementById("kpiOnline").textContent=d.domiciliarios_online||0;document.getElementById("kpiDisponibles").textContent=disponibles;document.getElementById("kpiVentas").textContent=money(d.ventas_hoy||0);var miniPendientes=document.getElementById("miniPendientes"),miniPreparacion=document.getElementById("miniPreparacion"),miniRuta=document.getElementById("miniRuta"),miniDisponibles=document.getElementById("miniDisponibles");if(miniPendientes)miniPendientes.textContent=pendientes;if(miniPreparacion)miniPreparacion.textContent=preparacion;if(miniRuta)miniRuta.textContent=ruta;if(miniDisponibles)miniDisponibles.textContent=disponibles}
  function renderRestaurants(){document.getElementById("restaurantsList").innerHTML=state.restaurants.map(function(r){return '<article class="dom-item"><strong>'+esc(r.nombre)+' <span class="dom-badge">'+esc(r.estado)+'</span></strong><small>'+esc(r.categoria||"Restaurante")+' | '+esc(r.codigo)+' | PIN configurado | '+(r.acepta_pedidos?"Acepta pedidos":"Pausado")+'</small><div class="dom-actions" style="margin-top:8px"><button class="btn secondary" data-edit-rest="'+r.id+'">Editar</button></div></article>'}).join("")||'<div class="dom-item">Sin restaurantes.</div>';var sel=document.getElementById("menuRestaurant");sel.innerHTML=state.restaurants.map(function(r){return '<option value="'+r.id+'">'+esc(r.nombre)+'</option>'}).join("")}
  function renderCouriers(){document.getElementById("couriersList").innerHTML=state.couriers.map(function(c){return '<article class="dom-item"><strong>'+esc(c.nombre)+' <span class="dom-badge">'+(c.online?"Online":"Offline")+'</span></strong><small>'+esc(c.documento)+' | '+esc(c.vehiculo_tipo||"Vehículo")+' '+esc(c.vehiculo_placa||"")+' | '+(c.disponible?"Disponible":"Ocupado")+'</small><div class="dom-actions" style="margin-top:8px"><button class="btn secondary" data-edit-courier="'+c.id+'">Editar</button></div></article>'}).join("")||'<div class="dom-item">Sin domiciliarios.</div>'}
  function renderMenu(){document.getElementById("menuList").innerHTML=state.menu.map(function(m){return '<article class="dom-item"><strong>'+esc(m.nombre)+' <span class="dom-badge">'+money(m.precio)+'</span></strong><small>'+esc(m.restaurant_nombre)+' | '+esc(m.categoria||"Menu")+' | '+(m.disponible?"Disponible":"Oculto")+'</small><div class="dom-actions" style="margin-top:8px"><button class="btn secondary" data-edit-menu="'+m.id+'">Editar</button></div></article>'}).join("")||'<div class="dom-item">Sin productos.</div>'}
  function renderOrders(){document.getElementById("ordersList").innerHTML=state.orders.map(function(o){return '<article class="dom-item"><strong>'+esc(o.codigo_pedido)+' | '+esc(o.cliente_nombre)+' <span class="dom-badge">'+esc(o.estado)+'</span></strong><small>'+esc(o.restaurant_nombre)+' -> '+esc(o.cliente_direccion)+' | '+money(o.total)+' | Código: '+esc(o.codigo_entrega||"-")+'</small><div class="dom-actions" style="margin-top:8px"><button class="btn secondary" data-dispatch="'+o.id+'">Asignar</button><button class="btn secondary" data-state="'+o.id+'" data-next="confirmado">Confirmar</button><button class="btn secondary" data-state="'+o.id+'" data-next="listo">Listo</button><button class="btn secondary" data-state="'+o.id+'" data-next="cancelado">Cancelar</button></div></article>'}).join("")||'<div class="dom-item">Sin pedidos.</div>';document.getElementById("offersList").innerHTML=state.offers.slice(0,6).map(function(o){return '<div class="dom-item"><strong>Oferta #'+o.order_id+'</strong><small>'+esc(o.courier_nombre)+' | '+esc(o.estado)+' | '+o.distancia_km+' km</small></div>'}).join("")}
  function drawMap(){layer.clearLayers();var bounds=[];state.restaurants.forEach(function(r){if(r.latitud&&r.longitud){var m=L.marker([r.latitud,r.longitud]).bindPopup("Restaurante: "+esc(r.nombre));m.addTo(layer);bounds.push([r.latitud,r.longitud])}});state.couriers.forEach(function(c){if(c.ultima_latitud&&c.ultima_longitud){var m=L.circleMarker([c.ultima_latitud,c.ultima_longitud],{radius:8,color:c.disponible?"#16a34a":"#f59e0b"}).bindPopup("Domiciliario: "+esc(c.nombre));m.addTo(layer);bounds.push([c.ultima_latitud,c.ultima_longitud])}});state.orders.forEach(function(o){if(o.cliente_latitud&&o.cliente_longitud){var m=L.circleMarker([o.cliente_latitud,o.cliente_longitud],{radius:7,color:"#ef4444"}).bindPopup("Cliente: "+esc(o.cliente_nombre));m.addTo(layer);bounds.push([o.cliente_latitud,o.cliente_longitud])}});if(bounds.length)map.fitBounds(bounds,{padding:[30,30]})}
  async function load(){try{var d=await api("dashboard");state.restaurants=d.restaurants||[];state.couriers=d.couriers||[];state.orders=d.orders||[];state.offers=d.offers||[];fillKpis(d);renderRestaurants();renderCouriers();renderOrders();drawMap();state.menu=await api("menu");renderMenu();fillConfig(await api("config"));renderCoreIntegration();msg("Domicilios actualizado.")}catch(e){msg(e.message,true)}}

  document.querySelectorAll("[data-tab]").forEach(function(b){b.onclick=function(){setTab(b.dataset.tab)}});
  document.querySelectorAll("[data-dom-go]").forEach(function(b){b.onclick=function(){setTab(b.dataset.domGo)}});
  document.getElementById("refreshBtn").onclick=load;
  document.getElementById("seedBtn").onclick=async function(){try{await post("seed_demo",{});await load();msg("Demo cargada. PIN restaurante y domiciliarios: 1234.")}catch(e){msg(e.message,true)}};
  document.getElementById("domSyncCoreBtn").onclick=async function(){try{var r=await post("sincronizar_nucleo",{});state.integracionNucleo=r.integracion||r;renderCoreIntegration();await load();msg("Nucleo sincronizado para domicilios.")}catch(e){msg(e.message,true)}};
  document.getElementById("configForm").onsubmit=async function(e){e.preventDefault();try{await post("config",{nombre_sistema:cfgNombreSistema.value,nombre_portal:cfgNombrePortal.value,moneda:cfgMoneda.value,radio_cobertura_km:n(cfgCobertura.value),radio_asignacion_km:n(cfgAsignacion.value),domiciliarios_por_ronda:n(cfgRonda.value),tarifa_base:n(cfgTarifaBase.value),tarifa_km:n(cfgTarifaKm.value),comision_porcentaje:n(cfgComision.value),auto_asignar:cfgAuto.checked,permitir_pedidos_publicos:cfgPublico.checked,exigir_codigo_entrega:cfgCodigo.checked});await load();msg("Configuración guardada.")}catch(err){msg(err.message,true)}};
  document.getElementById("restaurantForm").onsubmit=async function(e){e.preventDefault();var payload={id:n(restId.value),codigo:restCodigo.value,nombre:restNombre.value,categoria:restCategoria.value,telefono:restTelefono.value,direccion:restDireccion.value,latitud:n(restLat.value),longitud:n(restLng.value),tiempo_preparacion_min:n(restPrep.value),acepta_pedidos:restAcepta.checked,pin:restPin.value,estado:"activo"};try{await post("restaurants",payload,payload.id?"PUT":"POST");restaurantForm.reset();restAcepta.checked=true;restId.value="";await load();msg("Restaurante guardado.")}catch(err){msg(err.message,true)}};
  document.getElementById("courierForm").onsubmit=async function(e){e.preventDefault();var payload={id:n(courierId.value),codigo:courierCodigo.value,nombre:courierNombre.value,documento:courierDocumento.value,telefono:courierTelefono.value,vehiculo_tipo:courierVehiculo.value,vehiculo_placa:courierPlaca.value,pin:courierPin.value,estado:"activo"};try{await post("couriers",payload,payload.id?"PUT":"POST");courierForm.reset();courierId.value="";await load();msg("Domiciliario guardado.")}catch(err){msg(err.message,true)}};
  document.getElementById("menuForm").onsubmit=async function(e){e.preventDefault();try{await post("menu",{id:n(menuId.value),restaurant_id:n(menuRestaurant.value),codigo:menuCodigo.value,nombre:menuNombre.value,categoria:menuCategoria.value,precio:n(menuPrecio.value),descripcion:menuDescripcion.value,imagen_url:menuImagen.value,disponible:menuDisponible.checked});menuForm.reset();menuDisponible.checked=true;menuId.value="";await load();msg("Producto guardado.")}catch(err){msg(err.message,true)}};
  document.addEventListener("click",async function(e){var b=e.target.closest("button");if(!b)return;try{if(b.dataset.dispatch){await post("dispatch",{order_id:n(b.dataset.dispatch)});await load();msg("Pedido enviado a domiciliarios cercanos.")}if(b.dataset.state){await post("order_state",{order_id:n(b.dataset.state),state:b.dataset.next});await load()}if(b.dataset.editRest){var r=state.restaurants.find(x=>x.id==b.dataset.editRest);if(r){restId.value=r.id;restCodigo.value=r.codigo;restNombre.value=r.nombre;restCategoria.value=r.categoria||"";restTelefono.value=r.telefono||"";restDireccion.value=r.direccion||"";restLat.value=r.latitud||"";restLng.value=r.longitud||"";restPrep.value=r.tiempo_preparacion_min||20;restAcepta.checked=!!r.acepta_pedidos;setTab("restaurantes")}}if(b.dataset.editCourier){var c=state.couriers.find(x=>x.id==b.dataset.editCourier);if(c){courierId.value=c.id;courierCodigo.value=c.codigo;courierNombre.value=c.nombre;courierDocumento.value=c.documento;courierTelefono.value=c.telefono||"";courierVehiculo.value=c.vehiculo_tipo||"Moto";courierPlaca.value=c.vehiculo_placa||"";setTab("domiciliarios")}}if(b.dataset.editMenu){var m=state.menu.find(x=>x.id==b.dataset.editMenu);if(m){menuId.value=m.id;menuRestaurant.value=m.restaurant_id;menuCodigo.value=m.codigo||"";menuNombre.value=m.nombre;menuCategoria.value=m.categoria||"";menuPrecio.value=m.precio||0;menuDescripcion.value=m.descripcion||"";menuImagen.value=m.imagen_url||"";menuDisponible.checked=!!m.disponible;setTab("menu")}}}catch(err){msg(err.message,true)}});
  document.getElementById("restNew").onclick=function(){restaurantForm.reset();restId.value="";restAcepta.checked=true};
  document.getElementById("courierNew").onclick=function(){courierForm.reset();courierId.value=""};
  document.getElementById("menuNew").onclick=function(){menuForm.reset();menuId.value="";menuDisponible.checked=true};
  ["openCustomerPortal","openRestaurantPortal","openCourierPortal"].forEach(function(id){var el=document.getElementById(id);var page=id==="openCustomerPortal"?"/domicilios.html":id==="openRestaurantPortal"?"/domicilios_restaurante.html":"/domicilios_domiciliario.html";el.href=page+"?empresa_id="+encodeURIComponent(empresaId)});
  setTab(initialTabFromURL());
  load();setInterval(load,15000);
})();
