(function(){
  "use strict";
  var empresaId="";try{empresaId=(window.__resolveEmpresaIdContext&&window.__resolveEmpresaIdContext())||""}catch(e){}
  if(!empresaId){var qs=new URLSearchParams(location.search);empresaId=qs.get("empresa_id")||qs.get("id")||""}
  var state={cuentas:[],presupuestos:[],partidas:[],flujo:[],config:{}};
  var fmt=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
  function $(id){return document.getElementById(id)} function esc(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]})} function num(v){var n=Number(v);return Number.isFinite(n)?n:0} function money(v){try{return fmt.format(num(v))}catch(e){return "$"+num(v).toLocaleString("es-CO")}} function msg(t,e){$("tesMsg").textContent=t||"";$("tesMsg").classList.toggle("is-error",!!e)}
  async function api(action,opts){if(!empresaId)throw Error("No se encontró empresa_id.");var url="/api/empresa/tesoreria_presupuesto?empresa_id="+encodeURIComponent(empresaId)+(action?"&action="+encodeURIComponent(action):"");var res=await fetch(url,Object.assign({credentials:"same-origin"},opts||{}));var txt=await res.text(),data={};try{data=txt?JSON.parse(txt):{}}catch(e){data={raw:txt}}if(!res.ok)throw Error(data.error||data.raw||txt||("HTTP "+res.status));return data}
  function body(p){return{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p||{})}}
  function fill(d){$("kpiCuentas").textContent=d.cuentas_activas||0;$("kpiPres").textContent=d.presupuestos_activos||0;$("kpiSaldo").textContent=money(d.saldo_disponible);$("kpiIng").textContent=money(d.ingresos_proyectados);$("kpiEgr").textContent=money(d.egresos_proyectados);$("kpiNeto").textContent=money(d.flujo_neto);state.config=d.config||{};state.cuentas=d.cuentas||[];state.presupuestos=d.presupuestos||[];state.partidas=d.partidas||[];state.flujo=d.flujo||[];fillConfig();renderCuentas();renderPres();renderFlujo()}
  function fillConfig(){var c=state.config;$("cfgNombre").value=c.nombre_sistema||"Tesoreria y presupuesto";$("cfgMoneda").value=c.moneda||"COP";$("cfgPeriodo").value=c.periodo_trabajo||new Date().toISOString().slice(0,7);$("cfgMetodo").value=c.metodo_proyeccion||"mensual";$("cfgAlerta").checked=!!c.alerta_saldo_minimo;$("cfgAprobar").checked=!!c.requiere_aprobacion_pago}
  function renderCuentas(){$("cuentasList").innerHTML=state.cuentas.length?state.cuentas.map(function(c){return'<article class="tes-item"><div class="tes-top"><strong>'+esc(c.codigo)+" · "+esc(c.nombre)+'</strong><span class="tes-chip">'+esc(c.tipo)+'</span></div><div class="tes-muted">'+esc(c.entidad||"")+" "+esc(c.numero||"")+'</div><div><strong>'+money(c.saldo_actual)+'</strong> <span class="tes-muted">mínimo '+money(c.saldo_minimo)+'</span></div></article>'}).join(""):'<div class="tes-item">Sin cuentas registradas.</div>'}
  function renderPres(){var opts=state.presupuestos.map(function(p){return'<option value="'+p.id+'">'+esc(p.codigo)+" · "+esc(p.periodo)+'</option>'}).join("");$("partPres").innerHTML=opts||'<option value="">Sin presupuestos</option>';$("presList").innerHTML=state.presupuestos.length?state.presupuestos.map(function(p){var parts=state.partidas.filter(function(x){return String(x.presupuesto_id)===String(p.id)}).map(function(x){return'<div class="tes-muted">'+esc(x.tipo)+" · "+esc(x.concepto)+" · "+money(x.valor_presupuestado)+" / ejecutado "+money(x.valor_ejecutado)+'</div>'}).join("");return'<article class="tes-item"><div class="tes-top"><strong>'+esc(p.codigo)+" · "+esc(p.nombre)+'</strong><span class="tes-chip">'+esc(p.estado)+'</span></div><div class="tes-muted">'+esc(p.periodo)+" · ingresos "+money(p.ingresos_meta)+" · egresos "+money(p.egresos_meta)+'</div>'+parts+'<button class="tes-btn" type="button" data-gen="'+p.id+'">Generar flujo</button></article>'}).join(""):'<div class="tes-item">Sin presupuestos.</div>'}
  function renderFlujo(){var rows=state.flujo.map(function(f){return'<tr><td>'+esc(f.fecha_flujo)+'</td><td>'+esc(f.tipo)+'</td><td>'+esc(f.categoria)+'</td><td>'+esc(f.concepto)+'</td><td>'+money(f.valor)+'</td><td>'+money(f.valor_ejecutado)+'</td><td>'+esc(f.estado)+'</td></tr>'});$("flujoTable").innerHTML='<table class="tes-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Categoría</th><th>Concepto</th><th>Proyectado</th><th>Ejecutado</th><th>Estado</th></tr></thead><tbody>'+(rows.join("")||'<tr><td colspan="7">Sin flujo proyectado.</td></tr>')+'</tbody></table>'}
  async function load(){try{fill(await api("dashboard"));msg("Tesorería actualizada.")}catch(e){msg(e.message,true)}}
  document.addEventListener("click",async function(ev){var tab=ev.target.closest(".tes-tab");if(tab){document.querySelectorAll(".tes-tab").forEach(function(b){b.classList.toggle("is-active",b===tab)});document.querySelectorAll(".tes-panel").forEach(function(p){p.classList.toggle("is-active",p.id==="tab-"+tab.dataset.tab)});return}var gen=ev.target.closest("[data-gen]");if(gen){try{state.flujo=await api("generar_flujo",body({presupuesto_id:Number(gen.dataset.gen)}));renderFlujo();msg("Flujo generado.");document.querySelector('[data-tab="flujo"]').click()}catch(e){msg(e.message,true)}}});
  $("tesRefresh").onclick=load;$("tesSeed").onclick=async function(){try{await api("seed_demo",body({}));await load()}catch(e){msg(e.message,true)}};$("tesGenerar").onclick=async function(){try{var id=state.presupuestos[0]&&state.presupuestos[0].id;if(!id)throw Error("Crea o carga un presupuesto.");state.flujo=await api("generar_flujo",body({presupuesto_id:id}));renderFlujo();msg("Flujo generado.")}catch(e){msg(e.message,true)}};
  $("cuentaForm").onsubmit=async function(e){e.preventDefault();try{await api("cuentas",body({codigo:$("ctaCodigo").value,nombre:$("ctaNombre").value,tipo:$("ctaTipo").value,entidad:$("ctaEntidad").value,numero:$("ctaNumero").value,saldo_actual:num($("ctaSaldo").value),saldo_minimo:num($("ctaMinimo").value),estado:"activo"}));e.target.reset();await load()}catch(err){msg(err.message,true)}};
  $("presForm").onsubmit=async function(e){e.preventDefault();try{await api("presupuestos",body({codigo:$("presCodigo").value,nombre:$("presNombre").value,periodo:$("presPeriodo").value,ingresos_meta:num($("presIngresos").value),egresos_meta:num($("presEgresos").value),estado:"aprobado",responsable:$("presResp").value}));await load()}catch(err){msg(err.message,true)}};
  $("partidaForm").onsubmit=async function(e){e.preventDefault();try{await api("partidas",body({presupuesto_id:Number($("partPres").value),tipo:$("partTipo").value,categoria:$("partCat").value,concepto:$("partConcepto").value,valor_presupuestado:num($("partValor").value),valor_ejecutado:num($("partEjecutado").value),estado:"activo"}));await load()}catch(err){msg(err.message,true)}};
  $("configForm").onsubmit=async function(e){e.preventDefault();try{await api("config",body({nombre_sistema:$("cfgNombre").value,moneda:$("cfgMoneda").value,periodo_trabajo:$("cfgPeriodo").value,metodo_proyeccion:$("cfgMetodo").value,alerta_saldo_minimo:$("cfgAlerta").checked,requiere_aprobacion_pago:$("cfgAprobar").checked}));await load()}catch(err){msg(err.message,true)}};
  load();
})();
