(function(){
  'use strict';

  var guard=window.__empresaModuleGuard||{};
  var empresaId=typeof guard.resolveEmpresaId==='function'?Number(guard.resolveEmpresaId()):Number(new URLSearchParams(location.search).get('empresa_id')||0);
  var state={dashboard:null,gastos:[],suscripciones:[],precios:[],scannerStream:null,scannerActive:false};
  var money=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:2});
  var categoryLabels={supermercado:'Supermercado',alimentacion:'Alimentación',transporte:'Transporte',salud:'Salud',hogar:'Hogar',educacion:'Educación',familia:'Familia',entretenimiento:'Entretenimiento',servicios:'Servicios',ropa:'Ropa',mascotas:'Mascotas',otros:'Otros'};

  function el(id){return document.getElementById(id);}
  function today(){var d=new Date();function pad(value){return String(value).padStart(2,'0');}return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
  function currentMonth(){return today().slice(0,7);}
  function requestId(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():(Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));}
  function api(action,extra){var q=new URLSearchParams(extra||{});q.set('empresa_id',String(empresaId));q.set('action',action);return '/api/empresa/vida?'+q.toString();}
  function formatMoney(value,currency){try{return new Intl.NumberFormat('es-CO',{style:'currency',currency:String(currency||'COP'),maximumFractionDigits:2}).format(Number(value||0));}catch(_){return money.format(Number(value||0));}}
  function escapeText(value){return String(value==null?'':value);}
  function showMessage(text,type){var box=el('vidaMessage');box.textContent=text;box.className='vida-message '+(type==='error'?'is-error':'is-success');box.hidden=false;clearTimeout(showMessage.timer);showMessage.timer=setTimeout(function(){box.hidden=true;},6000);}
  function errorText(response){return response.text().then(function(text){text=String(text||'').trim();if(response.status===401)return 'Tu sesión terminó. Inicia sesión de nuevo.';if(response.status===403)return 'No tienes acceso a Vida en esta empresa.';if(response.status===503)return 'Vida requiere ejecutar la migración pendiente.';if(/^\s*</.test(text))text='';return text||('No se pudo completar la operación (HTTP '+response.status+').');});}
  function fetchJSON(url,options){return fetch(url,Object.assign({credentials:'same-origin'},options||{})).then(function(response){if(!response.ok)return errorText(response).then(function(message){throw new Error(message);});if(response.status===204)return null;return response.json();});}
  function setBusy(button,busy,label){if(!button)return;button.disabled=!!busy;if(busy){button.dataset.label=button.textContent;button.textContent=label||'Guardando...';}else if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label;}}

  function selectTab(name){document.querySelectorAll('[data-tab]').forEach(function(button){button.classList.toggle('is-active',button.dataset.tab===name);});document.querySelectorAll('[data-panel]').forEach(function(panel){panel.hidden=panel.dataset.panel!==name;});if(name==='gastos')loadExpenses();if(name==='precios')loadPrices();if(name==='suscripciones')loadSubscriptions();}

  function loadDashboard(){
    if(!empresaId){showMessage('Selecciona una empresa para abrir Vida.','error');return Promise.resolve();}
    return fetchJSON(api('dashboard',{mes:el('vidaMonth').value||currentMonth()})).then(function(data){state.dashboard=data;state.gastos=data.ultimos_gastos||[];state.suscripciones=data.suscripciones||[];renderDashboard(data);notifyAlerts(data.alertas||[]);}).catch(function(err){showMessage(err.message,'error');});
  }

  function renderDashboard(data){var r=data.resumen||{};el('vidaTotalMonth').textContent=formatMoney(r.total_mes);el('vidaExpenseCount').textContent=String(r.cantidad_gastos||0)+' registros';el('vidaDailyAverage').textContent=formatMoney(r.promedio_diario);el('vidaSubscriptionMonth').textContent=formatMoney(r.suscripciones_mensual);el('vidaSubscriptionCount').textContent=String(r.suscripciones_activas||0)+' activas';el('vidaSubscriptionYear').textContent=formatMoney(r.suscripciones_anual);el('vidaAlertCount').textContent=String((data.alertas||[]).length);renderCategories(r.por_categoria||[],Number(r.total_mes||0));renderAlerts(data.alertas||[]);renderExpenses(el('vidaRecentExpenses'),data.ultimos_gastos||[],true);}
  function renderCategories(items,total){var root=el('vidaCategoryChart');root.replaceChildren();if(!items.length){root.appendChild(emptyNode('Aún no tienes gastos en este mes.'));return;}items.forEach(function(item){var row=document.createElement('div');row.className='vida-category-row';var label=document.createElement('span');label.className='vida-category-label';label.textContent=categoryLabels[item.categoria]||item.categoria;var track=document.createElement('div');track.className='vida-category-track';var bar=document.createElement('div');bar.className='vida-category-bar';bar.style.width=Math.max(4,Math.min(100,total?Number(item.total||0)*100/total:0))+'%';track.appendChild(bar);var value=document.createElement('strong');value.className='vida-category-value';value.textContent=formatMoney(item.total);row.append(label,track,value);root.appendChild(row);});}
  function renderAlerts(items){var root=el('vidaAlerts');root.replaceChildren();if(!items.length){root.appendChild(emptyNode('Todo tranquilo. No hay cobros dentro del periodo de aviso.'));return;}items.forEach(function(item){var card=document.createElement('div');card.className='vida-alert'+(Number(item.dias_restantes)<0?' is-overdue':'');var strong=document.createElement('strong');strong.textContent=item.mensaje;var small=document.createElement('small');small.textContent='Fecha: '+item.fecha;card.append(strong,small);root.appendChild(card);});}
  function emptyNode(text){var node=document.createElement('div');node.className='vida-empty';node.textContent=text;return node;}

  function loadExpenses(){var query={limit:'300'};if(el('vidaFilterFrom').value)query.desde=el('vidaFilterFrom').value;if(el('vidaFilterTo').value)query.hasta=el('vidaFilterTo').value;return fetchJSON(api('gastos',query)).then(function(data){state.gastos=data.items||[];renderExpenses(el('vidaExpenses'),state.gastos,false);}).catch(function(err){showMessage(err.message,'error');});}
  function renderExpenses(root,items,compact){root.replaceChildren();if(!items.length){root.appendChild(emptyNode('No hay gastos registrados para este periodo.'));return;}items.forEach(function(item){var row=document.createElement('div');row.className='vida-expense-row';var date=document.createElement('time');date.className='vida-expense-date';date.dateTime=item.fecha_gasto;date.textContent=item.fecha_gasto.slice(5).split('-').reverse().join('/');var main=document.createElement('div');main.className='vida-expense-main';var title=document.createElement('strong');title.textContent=(item.comercio||categoryLabels[item.categoria]||'Gasto');var meta=document.createElement('small');meta.textContent=(categoryLabels[item.categoria]||item.categoria)+(item.descripcion?' · '+item.descripcion:'')+' · '+item.metodo_pago;main.append(title,meta);var amount=document.createElement('div');amount.className='vida-expense-amount';amount.textContent=formatMoney(item.monto,item.moneda);var actions=document.createElement('div');actions.className='vida-row-actions';if(item.recibo_disponible){var receipt=document.createElement('a');receipt.className='vida-icon-btn';receipt.href=item.recibo_url;receipt.target='_blank';receipt.rel='noopener';receipt.textContent='Factura';actions.appendChild(receipt);}if(!compact){actions.append(actionButton('Editar','edit-expense',item.id),actionButton('Eliminar','delete-expense',item.id,'danger'));}row.append(date,main,amount,actions);root.appendChild(row);});}
  function actionButton(text,action,id,className){var button=document.createElement('button');button.type='button';button.className='vida-icon-btn '+(className||'');button.dataset.action=action;button.dataset.id=String(id);button.textContent=text;return button;}

  function openExpense(item){var dialog=el('vidaExpenseDialog');el('vidaExpenseForm').reset();el('vidaExpenseId').value=item&&item.id||'';el('vidaExpenseTitle').textContent=item?'Editar gasto':'Registrar gasto';el('vidaExpenseDate').value=item&&item.fecha_gasto||today();el('vidaExpenseCategory').value=item&&item.categoria||'supermercado';el('vidaExpenseMerchant').value=item&&item.comercio||'';el('vidaExpenseAmount').value=item&&item.monto||'';el('vidaExpensePayment').value=item&&item.metodo_pago||'efectivo';el('vidaExpenseCurrency').value=item&&item.moneda||'COP';el('vidaExpenseDescription').value=item&&item.descripcion||'';el('vidaExpenseReceipt').disabled=!!item;el('vidaReceiptLabel').hidden=!!item;el('vidaReceiptName').textContent=item&&item.recibo_disponible?'La factura actual se conserva.':'Sin factura adjunta';dialog.showModal();}
  function saveExpense(event){event.preventDefault();var id=Number(el('vidaExpenseId').value||0);var button=el('vidaExpenseSave');setBusy(button,true);var promise;if(id){var payload={id:id,fecha_gasto:el('vidaExpenseDate').value,categoria:el('vidaExpenseCategory').value,comercio:el('vidaExpenseMerchant').value,monto:Number(el('vidaExpenseAmount').value),moneda:el('vidaExpenseCurrency').value,metodo_pago:el('vidaExpensePayment').value,descripcion:el('vidaExpenseDescription').value};promise=fetchJSON(api('gasto'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}else{var data=new FormData(el('vidaExpenseForm'));data.set('client_request_id',requestId());promise=fetchJSON(api('gasto'),{method:'POST',body:data});}promise.then(function(){el('vidaExpenseDialog').close();showMessage(id?'Gasto actualizado.':'Gasto registrado.','success');return Promise.all([loadDashboard(),loadExpenses()]);}).catch(function(err){showMessage(err.message,'error');}).finally(function(){setBusy(button,false);});}
  function deleteExpense(id){if(!confirm('¿Eliminar este gasto y su factura adjunta? Esta acción no se puede deshacer.'))return;fetchJSON(api('gasto',{id:String(id)}),{method:'DELETE'}).then(function(){showMessage('Gasto eliminado.','success');return Promise.all([loadDashboard(),loadExpenses()]);}).catch(function(err){showMessage(err.message,'error');});}

  function loadPrices(){var query={limit:'300'};var code=el('vidaPriceCodeFilter').value.trim();var product=el('vidaPriceNameFilter').value.trim();if(code)query.codigo_barras=code;if(product)query.producto=product;return fetchJSON(api('precios',query)).then(function(data){state.precios=data.items||[];renderPrices(state.precios);}).catch(function(err){showMessage(err.message,'error');});}
  function renderPrices(items){var root=el('vidaPrices');root.replaceChildren();if(!items.length){root.appendChild(emptyNode('Aún no hay precios. Registra un producto manualmente, escanea su código o carga una factura con IA.'));return;}var groups={};items.forEach(function(item){var key=item.codigo_barras||String(item.producto_nombre||'').toLowerCase();if(!groups[key])groups[key]=[];groups[key].push(item);});Object.keys(groups).forEach(function(key){var rows=groups[key];var newest=rows[0];var oldest=rows[rows.length-1];var card=document.createElement('article');card.className='vida-price-card';var header=document.createElement('header');var title=document.createElement('div');var strong=document.createElement('strong');strong.textContent=newest.producto_nombre;var code=document.createElement('small');code.textContent=newest.codigo_barras?'Código '+newest.codigo_barras:'Sin código de barras';title.append(strong,code);var trend=document.createElement('span');trend.className='vida-price-trend';var change=Number(newest.precio_unitario||0)-Number(oldest.precio_unitario||0);trend.textContent=rows.length>1?(change===0?'Sin cambio':(change>0?'Subió ':'Bajó ')+formatMoney(Math.abs(change),newest.moneda)):'Primer precio';header.append(title,trend);var list=document.createElement('div');list.className='vida-price-points';rows.slice(0,12).forEach(function(item){var row=document.createElement('div');var date=document.createElement('time');date.dateTime=item.fecha_compra;date.textContent=item.fecha_compra;var merchant=document.createElement('span');merchant.textContent=item.comercio||'Sin comercio';var price=document.createElement('strong');price.textContent=formatMoney(item.precio_unitario,item.moneda);row.append(date,merchant,price);list.appendChild(row);});card.append(header,list);root.appendChild(card);});}

  function loadSubscriptions(){return fetchJSON(api('suscripciones')).then(function(data){state.suscripciones=data.items||[];renderSubscriptions(state.suscripciones);renderAlerts(data.alertas||[]);}).catch(function(err){showMessage(err.message,'error');});}
  function renderSubscriptions(items){var root=el('vidaSubscriptions');root.replaceChildren();var annual=0;if(!items.length){root.appendChild(emptyNode('Aún no tienes suscripciones registradas.'));el('vidaSubscriptionYear').textContent=formatMoney(0);return;}items.forEach(function(item){if(item.estado==='activa')annual+=Number(item.costo_anual||0);var card=document.createElement('article');card.className='vida-subscription';var header=document.createElement('header');var title=document.createElement('h3');title.textContent=item.nombre;var chip=document.createElement('span');chip.className='vida-chip';chip.textContent=item.estado;header.append(title,chip);var price=document.createElement('div');price.className='vida-subscription-price';price.textContent=formatMoney(item.costo,item.moneda)+' ';var period=document.createElement('small');period.textContent='/ '+item.periodicidad;price.appendChild(period);var dl=document.createElement('dl');[['Próximo cobro',item.proxima_renovacion],['Aviso',item.recordatorio_dias+' día(s) antes'],['Proyección anual',formatMoney(item.costo_anual,item.moneda)],['Renovación automática',item.auto_renovacion?'Sí':'No']].forEach(function(pair){var dt=document.createElement('dt');dt.textContent=pair[0];var dd=document.createElement('dd');dd.textContent=pair[1];dl.append(dt,dd);});var footer=document.createElement('footer');footer.append(actionButton('Renovada','renew-subscription',item.id),actionButton('Editar','edit-subscription',item.id),actionButton('Eliminar','delete-subscription',item.id,'danger'));card.append(header,price,dl,footer);root.appendChild(card);});el('vidaSubscriptionYear').textContent=formatMoney(annual);}
  function openSubscription(item){el('vidaSubscriptionForm').reset();el('vidaSubscriptionId').value=item&&item.id||'';el('vidaSubscriptionTitle').textContent=item?'Editar suscripción':'Nueva suscripción';el('vidaSubscriptionName').value=item&&item.nombre||'';el('vidaSubscriptionProvider').value=item&&item.proveedor||'';el('vidaSubscriptionCost').value=item&&item.costo||'';el('vidaSubscriptionCurrency').value=item&&item.moneda||'COP';el('vidaSubscriptionPeriod').value=item&&item.periodicidad||'mensual';el('vidaSubscriptionInterval').value=item&&item.intervalo||1;el('vidaSubscriptionStart').value=item&&item.fecha_inicio||today();el('vidaSubscriptionNext').value=item&&item.proxima_renovacion||today();el('vidaSubscriptionReminder').value=item&&item.recordatorio_dias!=null?item.recordatorio_dias:5;el('vidaSubscriptionReminderType').value=item&&item.tipo_recordatorio||'renovar';el('vidaSubscriptionState').value=item&&item.estado||'activa';el('vidaSubscriptionAuto').checked=item?!!item.auto_renovacion:true;el('vidaSubscriptionNotes').value=item&&item.notas||'';el('vidaSubscriptionDialog').showModal();}
  function subscriptionPayload(){return{id:Number(el('vidaSubscriptionId').value||0),nombre:el('vidaSubscriptionName').value,proveedor:el('vidaSubscriptionProvider').value,costo:Number(el('vidaSubscriptionCost').value),moneda:el('vidaSubscriptionCurrency').value,periodicidad:el('vidaSubscriptionPeriod').value,intervalo:Number(el('vidaSubscriptionInterval').value),fecha_inicio:el('vidaSubscriptionStart').value,proxima_renovacion:el('vidaSubscriptionNext').value,recordatorio_dias:Number(el('vidaSubscriptionReminder').value),tipo_recordatorio:el('vidaSubscriptionReminderType').value,auto_renovacion:el('vidaSubscriptionAuto').checked,estado:el('vidaSubscriptionState').value,notas:el('vidaSubscriptionNotes').value};}
  function saveSubscription(event){event.preventDefault();var payload=subscriptionPayload();var button=el('vidaSubscriptionSave');setBusy(button,true);var options={method:payload.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};if(!payload.id)options.headers['Idempotency-Key']=requestId();fetchJSON(api('suscripcion'),options).then(function(){el('vidaSubscriptionDialog').close();showMessage(payload.id?'Suscripción actualizada.':'Suscripción creada.','success');return Promise.all([loadDashboard(),loadSubscriptions()]);}).catch(function(err){showMessage(err.message,'error');}).finally(function(){setBusy(button,false);});}
  function renewSubscription(id){if(!confirm('¿Marcar la suscripción como renovada y calcular su próxima fecha?'))return;fetchJSON(api('renovar',{id:String(id)}),{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(function(data){showMessage('Próxima renovación: '+data.proxima_renovacion,'success');return Promise.all([loadDashboard(),loadSubscriptions()]);}).catch(function(err){showMessage(err.message,'error');});}
  function deleteSubscription(id){if(!confirm('¿Eliminar esta suscripción?'))return;fetchJSON(api('suscripcion',{id:String(id)}),{method:'DELETE'}).then(function(){showMessage('Suscripción eliminada.','success');return Promise.all([loadDashboard(),loadSubscriptions()]);}).catch(function(err){showMessage(err.message,'error');});}

  function requestNotifications(){if(!('Notification'in window)){showMessage('Este navegador no admite alarmas del sistema. Los avisos seguirán visibles dentro de Vida.','error');return;}Notification.requestPermission().then(function(permission){showMessage(permission==='granted'?'Alarmas activadas.':'El navegador no autorizó las alarmas.',permission==='granted'?'success':'error');if(permission==='granted'&&state.dashboard)notifyAlerts(state.dashboard.alertas||[]);});}
  function notifyAlerts(items){if(!('Notification'in window)||Notification.permission!=='granted')return;items.forEach(function(item){var key='pcs_vida_alert_'+empresaId+'_'+item.suscripcion_id+'_'+item.fecha;try{if(localStorage.getItem(key))return;new Notification('Vida · Suscripción',{body:item.mensaje,tag:key});localStorage.setItem(key,new Date().toISOString());}catch(_){}});}

  function openAIInvoice(){el('vidaAIForm').reset();el('vidaAIInvoiceName').textContent='Sin factura seleccionada';el('vidaAIDialog').showModal();}
  function registerAIInvoice(event){event.preventDefault();var file=el('vidaAIInvoice').files&&el('vidaAIInvoice').files[0];if(!file){showMessage('Selecciona una foto o PDF de la factura.','error');return;}var button=el('vidaAISubmit');setBusy(button,true,'La IA está leyendo...');var data=new FormData(el('vidaAIForm'));data.set('client_request_id',requestId());fetchJSON(api('factura_ia'),{method:'POST',body:data}).then(function(response){el('vidaAIDialog').close();var result=response.resultado||{};var review=result.requiere_revision?' Revisa los datos: la confianza fue '+Math.round(Number(result.confianza||0)*100)+'%.':'';var message=response.created===false?'La factura ya estaba registrada; se devolvió el resultado anterior.':'Factura registrada automáticamente con '+String((result.precios||[]).length)+' producto(s).';showMessage(message+review,result.requiere_revision?'error':'success');return Promise.all([loadDashboard(),loadExpenses(),loadPrices()]);}).catch(function(err){showMessage(err.message,'error');}).finally(function(){setBusy(button,false);});}

  function stopScanner(){state.scannerActive=false;if(state.scannerStream){state.scannerStream.getTracks().forEach(function(track){track.stop();});state.scannerStream=null;}var video=el('vidaScannerVideo');if(video)video.srcObject=null;}
  function closeScanner(){stopScanner();if(el('vidaScannerDialog').open)el('vidaScannerDialog').close();}
  function openScanner(){if(!('BarcodeDetector'in window)){showMessage('Este navegador no admite lectura directa. Puedes escribir el código manualmente o usar Chrome/Edge actualizado en Android.','error');el('vidaExpenseBarcode').focus();return;}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){showMessage('La cámara no está disponible en este contexto. Usa HTTPS o escribe el código manualmente.','error');return;}el('vidaScannerDialog').showModal();el('vidaScannerStatus').textContent='Solicitando acceso a la cámara…';navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false}).then(function(stream){state.scannerStream=stream;state.scannerActive=true;var video=el('vidaScannerVideo');video.srcObject=stream;return video.play().then(function(){scanBarcodeFrame();});}).catch(function(){closeScanner();showMessage('No se pudo abrir la cámara. Puedes escribir el código manualmente.','error');});}
  function scanBarcodeFrame(){if(!state.scannerActive)return;var detector;try{detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','itf']});}catch(_){detector=new BarcodeDetector();}var video=el('vidaScannerVideo');detector.detect(video).then(function(codes){if(!state.scannerActive)return;if(codes&&codes[0]&&codes[0].rawValue){var value=String(codes[0].rawValue).replace(/\D/g,'').slice(0,80);if(value){el('vidaExpenseBarcode').value=value;closeScanner();showMessage('Código '+value+' leído correctamente.','success');return;}}el('vidaScannerStatus').textContent='Apunta la cámara al código y mantenla quieta.';setTimeout(scanBarcodeFrame,250);}).catch(function(){if(state.scannerActive)setTimeout(scanBarcodeFrame,400);});}

  function handleAction(event){var button=event.target.closest('[data-action]');if(!button)return;var id=Number(button.dataset.id||0);var action=button.dataset.action;if(action==='edit-expense')openExpense(state.gastos.find(function(item){return item.id===id;}));if(action==='delete-expense')deleteExpense(id);if(action==='edit-subscription')openSubscription(state.suscripciones.find(function(item){return item.id===id;}));if(action==='delete-subscription')deleteSubscription(id);if(action==='renew-subscription')renewSubscription(id);}
  function boot(){el('vidaMonth').value=currentMonth();document.querySelectorAll('[data-tab]').forEach(function(button){button.addEventListener('click',function(){selectTab(button.dataset.tab);});});document.querySelectorAll('[data-go-tab]').forEach(function(button){button.addEventListener('click',function(){selectTab(button.dataset.goTab);});});document.querySelectorAll('[data-open-expense]').forEach(function(button){button.addEventListener('click',function(){openExpense(null);});});document.querySelectorAll('[data-open-subscription]').forEach(function(button){button.addEventListener('click',function(){openSubscription(null);});});document.querySelectorAll('[data-close-dialog]').forEach(function(button){button.addEventListener('click',function(){button.closest('dialog').close();});});document.querySelectorAll('dialog').forEach(function(dialog){dialog.addEventListener('click',function(event){if(event.target===dialog){if(dialog.id==='vidaScannerDialog')stopScanner();dialog.close();}});});el('vidaMonth').addEventListener('change',loadDashboard);el('vidaFilterBtn').addEventListener('click',loadExpenses);el('vidaPriceFilterBtn').addEventListener('click',loadPrices);el('vidaExpenseForm').addEventListener('submit',saveExpense);el('vidaSubscriptionForm').addEventListener('submit',saveSubscription);el('vidaExpenseReceipt').addEventListener('change',function(){el('vidaReceiptName').textContent=this.files&&this.files[0]?this.files[0].name:'Sin factura adjunta';});el('vidaNotificationBtn').addEventListener('click',requestNotifications);el('vidaAIOpen').addEventListener('click',openAIInvoice);el('vidaAIForm').addEventListener('submit',registerAIInvoice);el('vidaAIInvoice').addEventListener('change',function(){el('vidaAIInvoiceName').textContent=this.files&&this.files[0]?this.files[0].name:'Sin factura seleccionada';});el('vidaScanOpen').addEventListener('click',openScanner);el('vidaScanClose').addEventListener('click',closeScanner);el('vidaScanCancel').addEventListener('click',closeScanner);document.addEventListener('visibilitychange',function(){if(document.hidden)stopScanner();});window.addEventListener('pagehide',stopScanner);el('vidaApp').addEventListener('click',handleAction);loadDashboard();}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
