package db

import (
	"strings"
	"testing"
	"time"
)

func TestCodigoDescuentoCreateAndResolve(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	vence := time.Now().Add(24 * time.Hour).Format("2006-01-02")
	id, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:         1,
		Codigo:            "",
		TipoDescuento:     "valor_fijo",
		Valor:             5000,
		Moneda:            "COP",
		MontoMinimoCompra: 10000,
		FechaVencimiento:  vence,
		UsosMaximos:       2,
		UsuarioCreador:    "test",
	})
	if err != nil {
		t.Fatalf("create codigo descuento: %v", err)
	}
	if id <= 0 {
		t.Fatalf("expected id > 0, got %d", id)
	}

	item, err := GetCodigoDescuentoByID(dbConn, 1, id)
	if err != nil {
		t.Fatalf("get codigo descuento: %v", err)
	}
	if strings.TrimSpace(item.Codigo) == "" {
		t.Fatal("expected autogenerated codigo")
	}

	aplicado, err := ResolveCodigoDescuentoParaMonto(dbConn, 1, item.Codigo, 15000)
	if err != nil {
		t.Fatalf("resolve codigo descuento: %v", err)
	}
	if aplicado.ValorAplicado != 5000 {
		t.Fatalf("expected valor aplicado 5000, got %.2f", aplicado.ValorAplicado)
	}
}

func TestCodigoDescuentoVencido(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	_, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:        1,
		Codigo:           "VENCIDO01",
		TipoDescuento:    "porcentaje",
		Valor:            15,
		FechaVencimiento: "2000-01-01",
		UsosMaximos:      1,
		UsuarioCreador:   "test",
	})
	if err != nil {
		t.Fatalf("create codigo descuento vencido: %v", err)
	}

	_, err = ResolveCodigoDescuentoParaMonto(dbConn, 1, "VENCIDO01", 12000)
	if err == nil {
		t.Fatal("expected error for expired discount code")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "vencido") {
		t.Fatalf("expected vencido error, got: %v", err)
	}
}
