package db

import (
	"strings"
	"testing"
	"time"
)

func TestCodigoDescuentoCreateAndResolve(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	vence := time.Now().Add(24 * time.Hour).Format("2006-01-02")
	id, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:         1,
		Codigo:            "",
		TipoDescuento:     "valor_fijo",
		Valor:             5000,
		Moneda:            "COP",
		MontoMinimoCompra: 10000,
		FechaVencimiento:  vence,
		UsosMaximos:       2,
		UsuarioCreador:    "test",
	})
	if err != nil {
		t.Fatalf("create codigo descuento: %v", err)
	}
	if id <= 0 {
		t.Fatalf("expected id > 0, got %d", id)
	}

	item, err := GetCodigoDescuentoByID(dbConn, 1, id)
	if err != nil {
		t.Fatalf("get codigo descuento: %v", err)
	}
	if strings.TrimSpace(item.Codigo) == "" {
		t.Fatal("expected autogenerated codigo")
	}

	aplicado, err := ResolveCodigoDescuentoParaMonto(dbConn, 1, item.Codigo, 15000)
	if err != nil {
		t.Fatalf("resolve codigo descuento: %v", err)
	}
	if aplicado.ValorAplicado != 5000 {
		t.Fatalf("expected valor aplicado 5000, got %.2f", aplicado.ValorAplicado)
	}
}

func TestCodigoDescuentoVencido(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	_, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:        1,
		Codigo:           "VENCIDO01",
		TipoDescuento:    "porcentaje",
		Valor:            15,
		FechaVencimiento: "2000-01-01",
		UsosMaximos:      1,
		UsuarioCreador:   "test",
	})
	if err != nil {
		t.Fatalf("create codigo descuento vencido: %v", err)
	}

	_, err = ResolveCodigoDescuentoParaMonto(dbConn, 1, "VENCIDO01", 12000)
	if err == nil {
		t.Fatal("expected error for expired discount code")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "vencido") {
		t.Fatalf("expected vencido error, got: %v", err)
	}
}

func TestCodigoDescuentoReglasContextoCanal(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	vence := time.Now().Add(24 * time.Hour).Format("2006-01-02")
	id, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:         1,
		Codigo:            "APPONLY01",
		TipoDescuento:     "valor_fijo",
		Valor:             3000,
		Moneda:            "COP",
		MontoMinimoCompra: 0,
		CanalVenta:        "app",
		HorarioDesde:      "00:00",
		HorarioHasta:      "23:59",
		DiasSemana:        "1,2,3,4,5,6,7",
		FechaVencimiento:  vence,
		UsosMaximos:       5,
		UsuarioCreador:    "test",
	})
	if err != nil {
		t.Fatalf("create codigo descuento canal: %v", err)
	}
	item, err := GetCodigoDescuentoByID(dbConn, 1, id)
	if err != nil {
		t.Fatalf("get codigo descuento canal: %v", err)
	}

	_, err = ResolveCodigoDescuentoParaMontoConContexto(dbConn, 1, item.Codigo, 10000, CodigoDescuentoContexto{CanalVenta: "mostrador"})
	if err == nil || !strings.Contains(strings.ToLower(err.Error()), "canal") {
		t.Fatalf("expected canal error, got: %v", err)
	}

	aplicado, err := ResolveCodigoDescuentoParaMontoConContexto(dbConn, 1, item.Codigo, 10000, CodigoDescuentoContexto{CanalVenta: "app"})
	if err != nil {
		t.Fatalf("resolve with canal app: %v", err)
	}
	if aplicado == nil || aplicado.ID <= 0 {
		t.Fatalf("expected applied discount with valid id")
	}
}

func TestCodigoDescuentoAntifraudeMaxUsosPorCliente(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	vence := time.Now().Add(24 * time.Hour).Format("2006-01-02")
	id, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:          1,
		Codigo:             "ANTI01",
		TipoDescuento:      "porcentaje",
		Valor:              10,
		Moneda:             "COP",
		MontoMinimoCompra:  0,
		MaxUsosPorCliente:  1,
		VentanaHorasFraude: 24,
		FechaVencimiento:   vence,
		UsosMaximos:        100,
		UsuarioCreador:     "test",
		SegmentoCliente:    "todos",
		CanalVenta:         "todos",
	})
	if err != nil {
		t.Fatalf("create antifraude code: %v", err)
	}
	item, err := GetCodigoDescuentoByID(dbConn, 1, id)
	if err != nil {
		t.Fatalf("get antifraude code: %v", err)
	}

	if _, err := dbConn.Exec(`INSERT INTO codigos_descuento_redenciones (
		empresa_id,
		codigo_descuento_id,
		carrito_id,
		cliente_id,
		codigo,
		canal_venta,
		segmento_cliente,
		monto_base,
		valor_descuento,
		estado_redencion,
		motivo,
		referencia_operacion,
		fecha_redencion,
		fecha_creacion,
		fecha_actualizacion,
		usuario_creador,
		estado,
		observaciones
	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'aplicada', ?, ?, datetime('now','localtime'), datetime('now','localtime'), datetime('now','localtime'), ?, 'activo', ?)`,
		1,
		id,
		11,
		9,
		item.Codigo,
		"app",
		"frecuente",
		15000,
		1500,
		"redencion previa",
		"test-ref",
		"test",
		"registro previo para antifraude",
	); err != nil {
		t.Fatalf("insert prior redemption: %v", err)
	}

	_, err = ResolveCodigoDescuentoParaMontoConContexto(dbConn, 1, item.Codigo, 12000, CodigoDescuentoContexto{
		ClienteID:  9,
		CanalVenta: "app",
		CarritoID:  22,
	})
	if err == nil || !strings.Contains(strings.ToLower(err.Error()), "limite de uso por cliente") {
		t.Fatalf("expected antifraude usage error, got: %v", err)
	}
}

func TestCodigoDescuentoRedencionSeRevierteAlReactivarCarrito(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaCarritosSchema(dbConn); err != nil {
		t.Fatalf("ensure carritos schema: %v", err)
	}
	if err := EnsureEmpresaCodigosDescuentoSchema(dbConn); err != nil {
		t.Fatalf("ensure codigos descuento schema: %v", err)
	}

	carritoID, err := CreateCarritoCompra(dbConn, CarritoCompra{
		EmpresaID:      1,
		Codigo:         "CAR-DESC-01",
		Nombre:         "Carrito Desc",
		CanalVenta:     "mostrador",
		ClienteID:      123,
		Moneda:         "COP",
		UsuarioCreador: "test",
		Estado:         "activo",
	})
	if err != nil {
		t.Fatalf("create carrito: %v", err)
	}
	if _, err := dbConn.Exec(`UPDATE carritos_compras SET total = 20000, subtotal = 20000 WHERE empresa_id = 1 AND id = ?`, carritoID); err != nil {
		t.Fatalf("set carrito totals: %v", err)
	}

	vence := time.Now().Add(24 * time.Hour).Format("2006-01-02")
	id, err := CreateCodigoDescuento(dbConn, CodigoDescuento{
		EmpresaID:         1,
		Codigo:            "TRACE01",
		TipoDescuento:     "valor_fijo",
		Valor:             5000,
		Moneda:            "COP",
		MontoMinimoCompra: 10000,
		FechaVencimiento:  vence,
		UsosMaximos:       10,
		UsuarioCreador:    "test",
	})
	if err != nil {
		t.Fatalf("create trace code: %v", err)
	}
	item, err := GetCodigoDescuentoByID(dbConn, 1, id)
	if err != nil {
		t.Fatalf("get trace code: %v", err)
	}

	aplicado, err := ResolveCodigoDescuentoParaMontoConContexto(dbConn, 1, item.Codigo, 20000, CodigoDescuentoContexto{
		CarritoID:  carritoID,
		ClienteID:  123,
		CanalVenta: "mostrador",
	})
	if err != nil {
		t.Fatalf("resolve trace code: %v", err)
	}

	if err := PayCarritoStationSession(dbConn, 1, carritoID, "efectivo", "REF-TRACE", "code", item.Codigo, aplicado.ValorAplicado, 0, 15000, id, "test"); err != nil {
		t.Fatalf("pay carrito with code: %v", err)
	}

	var usosTrasPago int64
	if err := dbConn.QueryRow(`SELECT COALESCE(usos_actuales, 0) FROM codigos_de_descuento WHERE empresa_id = 1 AND id = ?`, id).Scan(&usosTrasPago); err != nil {
		t.Fatalf("query usos after pay: %v", err)
	}
	if usosTrasPago != 1 {
		t.Fatalf("expected usos_actuales=1 after pay, got %d", usosTrasPago)
	}

	if err := ActivateCarritoStationSession(dbConn, 1, carritoID, false); err != nil {
		t.Fatalf("activate carrito session: %v", err)
	}

	var usosTrasRevert int64
	if err := dbConn.QueryRow(`SELECT COALESCE(usos_actuales, 0) FROM codigos_de_descuento WHERE empresa_id = 1 AND id = ?`, id).Scan(&usosTrasRevert); err != nil {
		t.Fatalf("query usos after revert: %v", err)
	}
	if usosTrasRevert != 0 {
		t.Fatalf("expected usos_actuales=0 after revert, got %d", usosTrasRevert)
	}

	rows, err := ListCodigoDescuentoRedencionesByEmpresa(dbConn, 1, id, "", 20)
	if err != nil {
		t.Fatalf("list redenciones: %v", err)
	}
	if len(rows) == 0 {
		t.Fatalf("expected at least one redencion record")
	}
	if strings.TrimSpace(strings.ToLower(rows[0].EstadoRedencion)) != "revertida" {
		t.Fatalf("expected latest redencion state revertida, got %q", rows[0].EstadoRedencion)
	}
}
