package db

func init() {
	for modulo, plantilla := range empresaModuloColombiaPlantillasPlantillas {
		empresaModuloColombiaTitulos[modulo] = plantilla.Titulo
	}
}

func buildVerticalPlantilla(titulo string, tipos, categorias, estados, acciones []string, etiquetaTercero, etiquetaReferencia, metadata string) EmpresaModuloColombiaPlantilla {
	return EmpresaModuloColombiaPlantilla{
		Titulo:             titulo,
		Tipos:              tipos,
		Categorias:         categorias,
		EstadosFlujo:       estados,
		AccionesSugeridas:  acciones,
		EtiquetaTercero:    etiquetaTercero,
		EtiquetaReferencia: etiquetaReferencia,
		MetadataEjemplo:    metadata,
	}
}

var empresaModuloColombiaPlantillasPlantillas = map[string]EmpresaModuloColombiaPlantilla{
	"agencia_viajes": buildVerticalPlantilla(
		"Agencia de viajes y planes turisticos",
		[]string{"paquete", "reserva", "itinerario", "cotizacion", "voucher", "comision"},
		[]string{"nacional", "internacional", "hotel", "vuelo", "tour", "seguro"},
		[]string{"borrador", "cotizado", "reservado", "pagado", "emitido", "cerrado", "cancelado"},
		[]string{"cotizacion", "reserva", "pago", "voucher", "seguimiento", "cierre"},
		"Cliente / proveedor",
		"Localizador / voucher",
		`{"destino":"Cartagena","pasajeros":2,"proveedor":"Operador demo","anticipo":50}`,
	),
	"operador_turistico": buildVerticalPlantilla(
		"Operador turistico local",
		[]string{"tour", "ruta", "guia", "transporte", "checkin", "incidencia"},
		[]string{"ciudad", "aventura", "cultural", "playa", "corporativo", "privado"},
		[]string{"programado", "confirmado", "en_ruta", "finalizado", "observado", "cancelado"},
		[]string{"programacion", "checkin", "asignacion_guia", "evidencia", "cierre"},
		"Cliente / guia",
		"Ruta / reserva",
		`{"ruta":"Centro historico","cupos":12,"guia":"Guia demo","punto_encuentro":"Hotel"}`,
	),
	"eventos_boleteria": buildVerticalPlantilla(
		"Eventos y boleteria",
		[]string{"evento", "boleta", "preventa", "aforo", "validacion_qr", "patrocinio"},
		[]string{"concierto", "conferencia", "deportivo", "feria", "privado", "corporativo"},
		[]string{"planeado", "en_venta", "agotado", "en_ingreso", "realizado", "cancelado"},
		[]string{"publicacion", "venta", "validacion", "control_aforo", "cierre"},
		"Cliente / promotor",
		"Evento / boleta QR",
		`{"aforo":500,"sector":"VIP","codigo_qr":"EVT-001","canal":"web"}`,
	),
	"salon_spa": buildVerticalPlantilla(
		"Salon de belleza, barberia y spa",
		[]string{"cita", "servicio", "paquete", "cabina", "insumo", "comision"},
		[]string{"cabello", "barberia", "unas", "spa", "estetica", "venta_producto"},
		[]string{"agendado", "confirmado", "en_servicio", "finalizado", "pagado", "cancelado"},
		[]string{"agendar", "confirmar", "consumo_insumo", "comision", "cierre"},
		"Cliente / profesional",
		"Cita / cabina",
		`{"profesional":"Estilista demo","duracion_min":60,"cabina":"Cabina 1","comision":30}`,
	),
	"veterinaria_petshop": buildVerticalPlantilla(
		"Veterinaria y pet shop",
		[]string{"mascota", "consulta", "vacuna", "peluqueria", "producto", "hospitalizacion"},
		[]string{"canino", "felino", "exotico", "alimento", "medicamento", "accesorio"},
		[]string{"agendado", "en_atencion", "observacion", "entregado", "facturado", "cancelado"},
		[]string{"historia", "vacunacion", "formula", "seguimiento", "cierre"},
		"Propietario / mascota",
		"Historia / vacuna",
		`{"mascota":"Luna","especie":"Canino","peso_kg":12.5,"proxima_vacuna":"2026-06-10"}`,
	),
	"clinica_consultorios": buildVerticalPlantilla(
		"Clinica medica y consultorios multiples",
		[]string{"paciente", "cita", "orden", "historia", "procedimiento", "remision"},
		[]string{"medicina_general", "especialista", "terapia", "urgencia", "control", "particular"},
		[]string{"agendado", "admitido", "en_consulta", "ordenado", "cerrado", "cancelado"},
		[]string{"admision", "consulta", "orden_medica", "evolucion", "cierre"},
		"Paciente / profesional",
		"Historia / autorizacion",
		`{"paciente":"Paciente demo","profesional":"Medico demo","eps":"Particular","triage":"bajo"}`,
	),
	"laboratorio_clinico": buildVerticalPlantilla(
		"Laboratorio clinico",
		[]string{"orden", "muestra", "resultado", "control_calidad", "entrega", "reproceso"},
		[]string{"hematologia", "quimica", "microbiologia", "inmunologia", "toma_muestra", "domicilio"},
		[]string{"ordenado", "muestra_tomada", "procesando", "validado", "entregado", "rechazado"},
		[]string{"toma_muestra", "procesamiento", "validacion", "entrega_resultado", "cierre"},
		"Paciente / convenio",
		"Orden / muestra",
		`{"muestra":"Sangre","codigo_barra":"LAB-001","ayuno":true,"validado_por":"Bacteriologo"}`,
	),
	"colegio_academia": buildVerticalPlantilla(
		"Colegio, academia o instituto",
		[]string{"estudiante", "matricula", "curso", "mensualidad", "asistencia", "boletin"},
		[]string{"preescolar", "primaria", "bachillerato", "tecnico", "idiomas", "refuerzo"},
		[]string{"preinscrito", "matriculado", "activo", "en_mora", "certificado", "retirado"},
		[]string{"matricula", "asistencia", "calificacion", "cobro", "certificado"},
		"Estudiante / acudiente",
		"Curso / matricula",
		`{"curso":"Ingles A1","jornada":"Tarde","acudiente":"Acudiente demo","mensualidad":180000}`,
	),
	"guarderia_infantil": buildVerticalPlantilla(
		"Guarderia y jardin infantil",
		[]string{"nino", "asistencia", "alimentacion", "autorizacion", "novedad", "pago"},
		[]string{"maternal", "caminadores", "parvulos", "prejardin", "transporte", "salud"},
		[]string{"registrado", "ingresado", "en_jornada", "entregado", "observado", "retirado"},
		[]string{"ingreso", "novedad", "autorizacion", "entrega", "cierre"},
		"Nino / acudiente",
		"Autorizacion / jornada",
		`{"acudiente":"Acudiente demo","alergias":"Ninguna","recoge":"Madre","lonchera":true}`,
	),
	"lavanderia_tintoreria": buildVerticalPlantilla(
		"Lavanderia y tintoreria",
		[]string{"orden", "prenda", "etiqueta", "lavado", "planchado", "entrega"},
		[]string{"lavado", "tintoreria", "planchado", "domicilio", "industrial", "delicado"},
		[]string{"recibido", "clasificado", "en_proceso", "listo", "entregado", "reclamacion"},
		[]string{"recepcion", "etiquetado", "control_calidad", "entrega", "reclamacion"},
		"Cliente / prenda",
		"Orden / etiqueta",
		`{"prendas":5,"peso_kg":3.2,"servicio":"Lavado y planchado","domicilio":false}`,
	),
	"taller_mecanico": buildVerticalPlantilla(
		"Taller mecanico, motos y autos",
		[]string{"orden_trabajo", "diagnostico", "repuesto", "mano_obra", "garantia", "entrega"},
		[]string{"moto", "automovil", "preventivo", "correctivo", "latoneria", "electrico"},
		[]string{"recibido", "diagnosticado", "aprobado", "en_taller", "listo", "entregado"},
		[]string{"diagnostico", "cotizacion", "aprobacion", "reparacion", "garantia", "cierre"},
		"Cliente / vehiculo",
		"Placa / orden",
		`{"placa":"ABC123","km":45200,"tecnico":"Mecanico demo","garantia_dias":30}`,
	),
	"transporte_carga_tms": buildVerticalPlantilla(
		"Transporte de carga / TMS",
		[]string{"flete", "manifiesto", "conductor", "vehiculo", "entrega", "novedad"},
		[]string{"urbano", "nacional", "refrigerado", "paqueteo", "contenedor", "ultima_milla"},
		[]string{"programado", "cargado", "en_ruta", "entregado", "liquidado", "cancelado"},
		[]string{"programacion", "cargue", "tracking", "entrega", "liquidacion"},
		"Cliente / conductor",
		"Manifiesto / placa",
		`{"origen":"Barranquilla","destino":"Cartagena","placa":"TRK001","peso_kg":1200}`,
	),
	"servicios_tecnicos": buildVerticalPlantilla(
		"Servicios tecnicos a domicilio",
		[]string{"orden_servicio", "visita", "diagnostico", "repuesto", "firma", "garantia"},
		[]string{"electrodomestico", "computo", "aire", "plomeria", "electricidad", "instalacion"},
		[]string{"solicitado", "programado", "en_visita", "cotizado", "finalizado", "garantia"},
		[]string{"programacion", "visita", "evidencia", "firma_cliente", "cierre"},
		"Cliente / tecnico",
		"Orden / equipo",
		`{"equipo":"Aire acondicionado","serial":"SER-001","tecnico":"Tecnico demo","firma":false}`,
	),
	"inmobiliaria_comercial": buildVerticalPlantilla(
		"Inmobiliaria comercial",
		[]string{"propiedad", "lead", "visita", "arriendo", "venta", "comision"},
		[]string{"apartamento", "casa", "local", "oficina", "lote", "bodega"},
		[]string{"captado", "publicado", "en_visita", "negociacion", "cerrado", "retirado"},
		[]string{"captacion", "publicacion", "visita", "oferta", "contrato", "cierre"},
		"Cliente / propietario",
		"Matricula / inmueble",
		`{"direccion":"Calle demo 123","canon":1800000,"asesor":"Asesor demo","comision":3}`,
	),
	"seguridad_privada": buildVerticalPlantilla(
		"Seguridad privada y vigilancia",
		[]string{"puesto", "turno", "guarda", "ronda_qr", "novedad", "incidente"},
		[]string{"residencial", "comercial", "industrial", "evento", "monitoreo", "escolta"},
		[]string{"programado", "en_turno", "novedad", "escalado", "cerrado", "cancelado"},
		[]string{"programacion", "ronda", "incidente", "escalamiento", "cierre"},
		"Cliente / guarda",
		"Puesto / ronda QR",
		`{"puesto":"Recepcion norte","guarda":"Guarda demo","rondas":6,"qr":"RND-001"}`,
	),
	"club_deportivo": buildVerticalPlantilla(
		"Club deportivo y escuela deportiva",
		[]string{"alumno", "clase", "disciplina", "torneo", "pago", "asistencia"},
		[]string{"futbol", "natacion", "gimnasia", "tenis", "baloncesto", "personalizado"},
		[]string{"inscrito", "activo", "en_clase", "competencia", "pagado", "suspendido"},
		[]string{"inscripcion", "asistencia", "plan_entrenamiento", "pago", "certificado"},
		"Alumno / entrenador",
		"Disciplina / categoria",
		`{"disciplina":"Futbol","categoria":"Sub 12","entrenador":"Coach demo","mensualidad":120000}`,
	),
	"funeraria_exequial": buildVerticalPlantilla(
		"Funeraria y servicios exequiales",
		[]string{"plan", "afiliado", "servicio", "sala", "contrato", "documento"},
		[]string{"prevision", "servicio_inmediato", "sala_velacion", "traslado", "documentos", "floristeria"},
		[]string{"afiliado", "solicitado", "en_servicio", "documentando", "cerrado", "anulado"},
		[]string{"afiliacion", "servicio", "documentacion", "autorizacion", "cierre"},
		"Afiliado / responsable",
		"Contrato / servicio",
		`{"plan":"Familiar","beneficiarios":4,"sala":"Sala 1","documentos":"pendiente"}`,
	),
	"parque_recreativo": buildVerticalPlantilla(
		"Parque recreativo y atracciones",
		[]string{"entrada", "manilla_qr", "atraccion", "aforo", "consumo", "incidente"},
		[]string{"general", "vip", "infantil", "atraccion", "alimentos", "evento"},
		[]string{"emitido", "ingresado", "en_parque", "consumido", "cerrado", "bloqueado"},
		[]string{"venta_entrada", "ingreso_qr", "control_aforo", "consumo", "cierre"},
		"Visitante / operador",
		"Manilla / entrada",
		`{"manilla":"PK-001","aforo_zona":120,"atracciones":5,"saldo_consumo":50000}`,
	),
	"cooperativa_fondo": buildVerticalPlantilla(
		"Cooperativa y fondo de empleados",
		[]string{"asociado", "aporte", "credito", "cartera", "beneficio", "asamblea"},
		[]string{"ahorro", "credito_libre", "calamidad", "educacion", "convenio", "solidaridad"},
		[]string{"solicitado", "en_estudio", "aprobado", "desembolsado", "en_cartera", "cerrado"},
		[]string{"radicacion", "estudio", "aprobacion", "desembolso", "recaudo", "cierre"},
		"Asociado / codeudor",
		"Credito / aporte",
		`{"asociado":"Asociado demo","monto":2500000,"plazo_meses":12,"tasa":"1.2%"}`,
	),
	"capacitacion_empresarial": buildVerticalPlantilla(
		"Centro de capacitacion empresarial",
		[]string{"curso", "cohorte", "inscripcion", "asistencia", "certificado", "empresa_cliente"},
		[]string{"seguridad", "ventas", "tecnologia", "liderazgo", "normativo", "induccion"},
		[]string{"programado", "abierto", "en_clase", "evaluado", "certificado", "cancelado"},
		[]string{"programacion", "inscripcion", "asistencia", "evaluacion", "certificacion"},
		"Estudiante / empresa",
		"Curso / certificado",
		`{"curso":"Servicio al cliente","horas":16,"instructor":"Instructor demo","certificado":true}`,
	),
}

var empresaModuloColombiaSeccionesPlantillas = map[string][]string{
	"agencia_viajes":           {"Dashboard comercial", "Paquetes y cotizaciones", "Reservas y vouchers", "Pagos y comisiones", "Aprobaciones", "Evidencias"},
	"operador_turistico":       {"Dashboard operativo", "Tours y rutas", "Guias y cupos", "Check-in", "Evidencias", "Cierre"},
	"eventos_boleteria":        {"Dashboard", "Eventos", "Boletas QR", "Aforo", "Validacion", "Reportes"},
	"salon_spa":                {"Agenda", "Servicios", "Profesionales", "Insumos", "Comisiones", "Cierre"},
	"veterinaria_petshop":      {"Pacientes", "Historia", "Vacunas", "Peluqueria", "Productos", "Seguimiento"},
	"clinica_consultorios":     {"Pacientes", "Citas", "Historia", "Ordenes", "Aprobaciones", "Reportes"},
	"laboratorio_clinico":      {"Ordenes", "Muestras", "Resultados", "Calidad", "Entrega", "SLA"},
	"colegio_academia":         {"Matriculas", "Cursos", "Asistencia", "Mensualidades", "Boletines", "Certificados"},
	"guarderia_infantil":       {"Jornada", "Ninos", "Acudientes", "Autorizaciones", "Novedades", "Pagos"},
	"lavanderia_tintoreria":    {"Recepcion", "Prendas", "Etiquetas", "Proceso", "Entrega", "Reclamos"},
	"taller_mecanico":          {"Ordenes", "Diagnostico", "Repuestos", "Mano de obra", "Garantias", "Entrega"},
	"transporte_carga_tms":     {"Fletes", "Manifiestos", "Conductores", "Tracking", "Entregas", "Liquidacion"},
	"servicios_tecnicos":       {"Ordenes", "Agenda", "Tecnicos", "Repuestos", "Firmas", "Garantias"},
	"inmobiliaria_comercial":   {"Propiedades", "Leads", "Visitas", "Contratos", "Comisiones", "Cierre"},
	"seguridad_privada":        {"Puestos", "Turnos", "Guardas", "Rondas QR", "Incidentes", "Reportes"},
	"club_deportivo":           {"Alumnos", "Disciplinas", "Clases", "Torneos", "Pagos", "Asistencia"},
	"funeraria_exequial":       {"Planes", "Afiliados", "Servicios", "Salas", "Documentos", "Cierre"},
	"parque_recreativo":        {"Entradas", "Manillas QR", "Aforo", "Atracciones", "Consumo", "Incidentes"},
	"cooperativa_fondo":        {"Asociados", "Aportes", "Creditos", "Cartera", "Beneficios", "Asambleas"},
	"capacitacion_empresarial": {"Cursos", "Cohortes", "Instructores", "Asistencia", "Evaluaciones", "Certificados"},
}

func GetEmpresaModuloColombiaSeccionesFlujo(modulo string) []string {
	modulo = NormalizeEmpresaModuloColombia(modulo)
	if rows, ok := empresaModuloColombiaSeccionesPlantillas[modulo]; ok {
		return append([]string{}, rows...)
	}
	return []string{"Dashboard", "Configuracion", "Registros", "Seguimiento", "Aprobaciones", "Evidencias"}
}
