package db

import (
	"database/sql"
	"errors"
	"strings"
	"testing"
)

func TestSoporteRemotoDBFlow(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaSoporteRemotoSchema(dbConn); err != nil {
		t.Fatalf("ensure soporte remoto schema: %v", err)
	}

	cfg, err := GetEmpresaSoporteRemotoConfig(dbConn, 61)
	if err != nil {
		t.Fatalf("get default config: %v", err)
	}
	if !cfg.Habilitado {
		t.Fatalf("expected default config habilitado=true")
	}
	if cfg.AutoCerrarMinutos <= 0 {
		t.Fatalf("expected default auto_cerrar_minutos > 0")
	}

	_, err = UpsertEmpresaSoporteRemotoConfig(dbConn, EmpresaSoporteRemotoConfig{
		EmpresaID:                  61,
		Habilitado:                 true,
		ProveedorPreferido:         "guacamole",
		ModoOperacion:              "agente_local",
		RequiereAprobacionOperador: false,
		AutoCerrarMinutos:          45,
		UsuarioCreador:             "qa@local",
		Estado:                     "activo",
		Observaciones:              "configuracion de test",
	})
	if err != nil {
		t.Fatalf("upsert config: %v", err)
	}

	deviceID, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      61,
		NombreEquipo:   "Caja Principal",
		AliasOperativo: "Punto 1",
		StreamURL:      "https://remote.example/novnc/vnc.html",
		UsuarioCreador: "qa@local",
		Estado:         "activo",
	}, "2580")
	if err != nil {
		t.Fatalf("create dispositivo: %v", err)
	}
	if deviceID <= 0 {
		t.Fatalf("expected device id > 0, got %d", deviceID)
	}

	device, err := GetEmpresaSoporteRemotoDispositivoByID(dbConn, 61, deviceID)
	if err != nil {
		t.Fatalf("get dispositivo by id: %v", err)
	}
	if strings.TrimSpace(device.CodigoDispositivo) == "" {
		t.Fatal("expected autogenerated codigo_dispositivo")
	}

	if _, err := ValidateEmpresaSoporteRemotoDispositivoAccess(dbConn, 61, device.CodigoDispositivo, "pin-invalido"); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows for wrong pin, got: %v", err)
	}

	heartbeatDevice, err := RegisterEmpresaSoporteRemotoDispositivoHeartbeat(dbConn, 61, device.CodigoDispositivo, "2580", "", "Windows 11", "1.0.1")
	if err != nil {
		t.Fatalf("register heartbeat: %v", err)
	}
	if heartbeatDevice.EstadoConexion != "online" {
		t.Fatalf("expected estado_conexion online, got %q", heartbeatDevice.EstadoConexion)
	}

	session, err := CreateEmpresaSoporteRemotoSession(dbConn, 61, deviceID, "admin@local", "Operador Uno", "operador@local", "Soporte de prueba", 25, false)
	if err != nil {
		t.Fatalf("create session: %v", err)
	}
	if strings.TrimSpace(session.TokenVisualizacionRaw) == "" {
		t.Fatal("expected token_visualizacion in created session")
	}
	if session.EstadoSesion != "activa" {
		t.Fatalf("expected estado_sesion activa, got %q", session.EstadoSesion)
	}

	if _, err := ResolveEmpresaSoporteRemotoViewerSession(dbConn, 61, session.CodigoSesion, "token-invalido"); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows for invalid token, got: %v", err)
	}

	resolved, err := ResolveEmpresaSoporteRemotoViewerSession(dbConn, 61, session.CodigoSesion, session.TokenVisualizacionRaw)
	if err != nil {
		t.Fatalf("resolve viewer session: %v", err)
	}
	if resolved.CodigoSesion != session.CodigoSesion {
		t.Fatalf("expected codigo_sesion %q, got %q", session.CodigoSesion, resolved.CodigoSesion)
	}
	if strings.TrimSpace(resolved.URLVisualizacion) == "" {
		t.Fatal("expected non-empty url_visualizacion in resolved session")
	}

	if err := SetEmpresaSoporteRemotoSessionEstadoByCodigo(dbConn, 61, session.CodigoSesion, "finalizada", "cierre de prueba"); err != nil {
		t.Fatalf("set session estado finalizada: %v", err)
	}
	finalState, err := GetEmpresaSoporteRemotoSessionByCodigo(dbConn, 61, session.CodigoSesion)
	if err != nil {
		t.Fatalf("get session by codigo: %v", err)
	}
	if finalState.EstadoSesion != "finalizada" {
		t.Fatalf("expected finalizada, got %q", finalState.EstadoSesion)
	}
}

func TestSoporteRemotoDBIsolationByEmpresa(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaSoporteRemotoSchema(dbConn); err != nil {
		t.Fatalf("ensure soporte remoto schema: %v", err)
	}

	deviceID, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      70,
		NombreEquipo:   "Recepcion",
		StreamURL:      "https://remote.example/device/70",
		UsuarioCreador: "admin@empresa70.local",
		Estado:         "activo",
	}, "7070")
	if err != nil {
		t.Fatalf("create device empresa 70: %v", err)
	}

	if _, err := GetEmpresaSoporteRemotoDispositivoByID(dbConn, 71, deviceID); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows querying foreign empresa device, got: %v", err)
	}

	if _, err := CreateEmpresaSoporteRemotoSession(dbConn, 71, deviceID, "otro@empresa.local", "Operador", "op@empresa.local", "No debe permitir cruce", 20, false); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows creating session with device from another empresa, got: %v", err)
	}
}
