package db

import (
	"database/sql"
	"errors"
	"strings"
	"testing"
)

func TestSoporteRemotoDBFlow(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaSoporteRemotoSchema(dbConn); err != nil {
		t.Fatalf("ensure soporte remoto schema: %v", err)
	}

	cfg, err := GetEmpresaSoporteRemotoConfig(dbConn, 61)
	if err != nil {
		t.Fatalf("get default config: %v", err)
	}
	if !cfg.Habilitado {
		t.Fatalf("expected default config habilitado=true")
	}
	if cfg.AutoCerrarMinutos <= 0 {
		t.Fatalf("expected default auto_cerrar_minutos > 0")
	}

	_, err = UpsertEmpresaSoporteRemotoConfig(dbConn, EmpresaSoporteRemotoConfig{
		EmpresaID:                  61,
		Habilitado:                 true,
		ProveedorPreferido:         "guacamole",
		ModoOperacion:              "agente_local",
		RequiereAprobacionOperador: false,
		AutoCerrarMinutos:          45,
		UsuarioCreador:             "qa@local",
		Estado:                     "activo",
		Observaciones:              "configuracion de test",
	})
	if err != nil {
		t.Fatalf("upsert config: %v", err)
	}

	deviceID, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      61,
		NombreEquipo:   "Caja Principal",
		AliasOperativo: "Punto 1",
		StreamURL:      "https://remote.example/novnc/vnc.html",
		UsuarioCreador: "qa@local",
		Estado:         "activo",
	}, "2580")
	if err != nil {
		t.Fatalf("create dispositivo: %v", err)
	}
	if deviceID <= 0 {
		t.Fatalf("expected device id > 0, got %d", deviceID)
	}

	device, err := GetEmpresaSoporteRemotoDispositivoByID(dbConn, 61, deviceID)
	if err != nil {
		t.Fatalf("get dispositivo by id: %v", err)
	}
	if strings.TrimSpace(device.CodigoDispositivo) == "" {
		t.Fatal("expected autogenerated codigo_dispositivo")
	}

	if _, err := ValidateEmpresaSoporteRemotoDispositivoAccess(dbConn, 61, device.CodigoDispositivo, "pin-invalido"); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows for wrong pin, got: %v", err)
	}

	heartbeatDevice, err := RegisterEmpresaSoporteRemotoDispositivoHeartbeat(dbConn, 61, device.CodigoDispositivo, "2580", "", "Windows 11", "1.0.1")
	if err != nil {
		t.Fatalf("register heartbeat: %v", err)
	}
	if heartbeatDevice.EstadoConexion != "online" {
		t.Fatalf("expected estado_conexion online, got %q", heartbeatDevice.EstadoConexion)
	}

	session, err := CreateEmpresaSoporteRemotoSession(dbConn, 61, deviceID, "admin@local", "Operador Uno", "operador@local", "Soporte de prueba", 25, false)
	if err != nil {
		t.Fatalf("create session: %v", err)
	}
	if strings.TrimSpace(session.TokenVisualizacionRaw) == "" {
		t.Fatal("expected token_visualizacion in created session")
	}
	if session.EstadoSesion != "activa" {
		t.Fatalf("expected estado_sesion activa, got %q", session.EstadoSesion)
	}

	if _, err := ResolveEmpresaSoporteRemotoViewerSession(dbConn, 61, session.CodigoSesion, "token-invalido"); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows for invalid token, got: %v", err)
	}

	resolved, err := ResolveEmpresaSoporteRemotoViewerSession(dbConn, 61, session.CodigoSesion, session.TokenVisualizacionRaw)
	if err != nil {
		t.Fatalf("resolve viewer session: %v", err)
	}
	if resolved.CodigoSesion != session.CodigoSesion {
		t.Fatalf("expected codigo_sesion %q, got %q", session.CodigoSesion, resolved.CodigoSesion)
	}
	if strings.TrimSpace(resolved.URLVisualizacion) == "" {
		t.Fatal("expected non-empty url_visualizacion in resolved session")
	}

	if err := SetEmpresaSoporteRemotoSessionEstadoByCodigo(dbConn, 61, session.CodigoSesion, "finalizada", "cierre de prueba"); err != nil {
		t.Fatalf("set session estado finalizada: %v", err)
	}
	finalState, err := GetEmpresaSoporteRemotoSessionByCodigo(dbConn, 61, session.CodigoSesion)
	if err != nil {
		t.Fatalf("get session by codigo: %v", err)
	}
	if finalState.EstadoSesion != "finalizada" {
		t.Fatalf("expected finalizada, got %q", finalState.EstadoSesion)
	}
}

func TestSoporteRemotoDBIsolationByEmpresa(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaSoporteRemotoSchema(dbConn); err != nil {
		t.Fatalf("ensure soporte remoto schema: %v", err)
	}

	deviceID, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      70,
		NombreEquipo:   "Recepcion",
		StreamURL:      "https://remote.example/device/70",
		UsuarioCreador: "admin@empresa70.local",
		Estado:         "activo",
	}, "7070")
	if err != nil {
		t.Fatalf("create device empresa 70: %v", err)
	}

	if _, err := GetEmpresaSoporteRemotoDispositivoByID(dbConn, 71, deviceID); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows querying foreign empresa device, got: %v", err)
	}

	if _, err := CreateEmpresaSoporteRemotoSession(dbConn, 71, deviceID, "otro@empresa.local", "Operador", "op@empresa.local", "No debe permitir cruce", 20, false); !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("expected sql.ErrNoRows creating session with device from another empresa, got: %v", err)
	}
}

func TestSoporteRemotoDBPlanLimitsAndBlockedAttempts(t *testing.T) {
	dbConn := openCarritoInventarioTestDB(t)
	if err := EnsureEmpresaSoporteRemotoSchema(dbConn); err != nil {
		t.Fatalf("ensure soporte remoto schema: %v", err)
	}

	if _, err := UpsertEmpresaSoporteRemotoConfig(dbConn, EmpresaSoporteRemotoConfig{
		EmpresaID:                  88,
		Habilitado:                 true,
		ProveedorPreferido:         "rustdesk_web",
		ModoOperacion:              "hibrido",
		RequiereAprobacionOperador: false,
		AutoCerrarMinutos:          30,
		MaxConexionesMes:           1,
		MaxMinutosMes:              1,
		MaxDispositivos:            1,
		UsuarioCreador:             "qa@local",
		Estado:                     "activo",
	}); err != nil {
		t.Fatalf("upsert config with limits: %v", err)
	}

	deviceID, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      88,
		NombreEquipo:   "Caja limitada",
		StreamURL:      "https://remote.example/limit-1",
		UsuarioCreador: "qa@local",
		Estado:         "activo",
	}, "8800")
	if err != nil {
		t.Fatalf("create first device: %v", err)
	}

	if _, err := CreateEmpresaSoporteRemotoDispositivo(dbConn, EmpresaSoporteRemotoDispositivo{
		EmpresaID:      88,
		NombreEquipo:   "Caja extra",
		StreamURL:      "https://remote.example/limit-2",
		UsuarioCreador: "qa@local",
		Estado:         "activo",
	}, "8801"); !errors.Is(err, ErrSoporteRemotoPlanLimit) {
		t.Fatalf("expected ErrSoporteRemotoPlanLimit for second device, got: %v", err)
	}

	session, err := CreateEmpresaSoporteRemotoSession(dbConn, 88, deviceID, "qa@local", "Mesa central", "mesa@local", "Sesion limitada", 1, false)
	if err != nil {
		t.Fatalf("create first limited session: %v", err)
	}
	if err := SetEmpresaSoporteRemotoSessionEstadoByCodigo(dbConn, 88, session.CodigoSesion, "finalizada", "cierre automatico test"); err != nil {
		t.Fatalf("finish limited session: %v", err)
	}

	if _, err := CreateEmpresaSoporteRemotoSession(dbConn, 88, deviceID, "qa@local", "Mesa central", "mesa@local", "Debe bloquear por plan", 1, false); !errors.Is(err, ErrSoporteRemotoPlanLimit) {
		t.Fatalf("expected ErrSoporteRemotoPlanLimit for second session, got: %v", err)
	}

	uso, err := GetEmpresaSoporteRemotoUso(dbConn, 88)
	if err != nil {
		t.Fatalf("get uso soporte remoto: %v", err)
	}
	if uso.SesionesMes != 1 {
		t.Fatalf("expected sesiones_mes=1, got %d", uso.SesionesMes)
	}
	if uso.IntentosBloqueadosMes != 1 {
		t.Fatalf("expected intentos_bloqueados_mes=1, got %d", uso.IntentosBloqueadosMes)
	}
	if uso.MinutosConsumidosMes < 1 {
		t.Fatalf("expected minutos_consumidos_mes >= 1, got %d", uso.MinutosConsumidosMes)
	}
	if uso.PuedeCrearSesion {
		t.Fatalf("expected puede_crear_sesion=false after limit")
	}
	if !strings.Contains(strings.ToLower(uso.BloqueoMotivo), "maximo") {
		t.Fatalf("expected bloqueo motivo with maximo, got %q", uso.BloqueoMotivo)
	}

	rows, total, err := ListEmpresaSoporteRemotoSesiones(dbConn, 88, EmpresaSoporteRemotoSessionFilter{Limit: 20})
	if err != nil {
		t.Fatalf("list sessions after blocked attempt: %v", err)
	}
	if total != 2 || len(rows) != 2 {
		t.Fatalf("expected 2 session rows including blocked attempt, got total=%d len=%d", total, len(rows))
	}
	if !rows[0].BloqueadaPorLimite && !rows[1].BloqueadaPorLimite {
		t.Fatalf("expected at least one blocked session attempt in rows")
	}
}
