version: "3.8"

services:
  pcs-nextcloud-db:
    image: postgres:16-alpine
    container_name: pcs-nextcloud-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    volumes:
      - pcs_nextcloud_db:/var/lib/postgresql/data

  pcs-nextcloud-redis:
    image: redis:7-alpine
    container_name: pcs-nextcloud-redis
    restart: unless-stopped
    volumes:
      - pcs_nextcloud_redis:/data

  pcs-nextcloud:
    image: nextcloud:29-apache
    container_name: pcs-nextcloud
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"
    depends_on:
      - pcs-nextcloud-db
      - pcs-nextcloud-redis
    environment:
      - POSTGRES_HOST=pcs-nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - REDIS_HOST=pcs-nextcloud-redis
      - TRUSTED_PROXIES=127.0.0.1
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.powerfulcontrolsystem.com
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.powerfulcontrolsystem.com
    volumes:
      - pcs_nextcloud_html:/var/www/html
      - pcs_nextcloud_data:/var/www/html/data

volumes:
  pcs_nextcloud_db:
  pcs_nextcloud_redis:
  pcs_nextcloud_html:
  pcs_nextcloud_data:
