// Small native WebGL renderer. No framework or external runtime dependency.
export const V={add:(a,b)=>a.map((x,i)=>x+b[i]),sub:(a,b)=>a.map((x,i)=>x-b[i]),dot:(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{const l=Math.hypot(...a)||1;return a.map(x=>x/l)}};
export function multiply(a,b){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let i=0;i<4;i++)out[c*4+r]+=a[i*4+r]*b[c*4+i];return out}
export function model(p=[0,0,0],s=[1,1,1],r=[0,0,0]){const [x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);const a=[cy*cz,cy*sz,-sy,0,sx*sy*cz-cx*sz,sx*sy*sz+cx*cz,sx*cy,0,cx*sy*cz+sx*sz,cx*sy*sz-sx*cz,cx*cy,0,...p,1];for(let c=0;c<3;c++)for(let row=0;row<3;row++)a[c*4+row]*=s[c];return new Float32Array(a)}
function view(eye,target){const z=V.norm(V.sub(eye,target)),x=V.norm(V.cross([0,1,0],z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1])}
function perspective(aspect){const f=1/Math.tan(68*Math.PI/360),n=.08,far=180;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0])}
const vertex=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec3 aColor;
uniform mat4 uModel,uVP,uLightVP;uniform mat3 uNormal;uniform float uTime,uKind;
varying vec3 vWorld,vNormal,vColor;varying vec4 vShadow;
void main(){vec4 world=uModel*vec4(aPosition,1.);if(uKind==1.){world.x+=sin(uTime*1.4+world.z*.6)*.10*max(0.,aPosition.y);world.z+=cos(uTime+world.x*.4)*.07*max(0.,aPosition.y);}vWorld=world.xyz;vNormal=normalize(uNormal*aNormal);vColor=aColor;vShadow=uLightVP*world;gl_Position=uVP*world;}`;
const fragment=`precision highp float;varying vec3 vWorld,vNormal,vColor;
uniform vec3 uColor,uEye,uFog;uniform float uTime,uKind,uFogDensity,uAlpha;uniform sampler2D uShadowMap;varying vec4 vShadow;
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);vec4 h=fract(sin(vec4(dot(i,vec2(127.1,311.7)),dot(i+vec2(1,0),vec2(127.1,311.7)),dot(i+vec2(0,1),vec2(127.1,311.7)),dot(i+vec2(1,1),vec2(127.1,311.7))))*43758.5453);return mix(mix(h.x,h.y,f.x),mix(h.z,h.w,f.x),f.y);}
float shadow(){vec3 sc=vShadow.xyz/vShadow.w*.5+.5;if(sc.x<0.||sc.x>1.||sc.y<0.||sc.y>1.)return 1.;float lit=0.;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){vec4 depthSample=texture2D(uShadowMap,sc.xy+vec2(x,y)/1536.);float depth=dot(depthSample,vec4(1.,1./255.,1./65025.,1./16581375.));lit+=sc.z-.0018<depth?1.:.32;}return lit/9.;}
void main(){vec3 n=normalize(vNormal);vec3 light=normalize(vec3(-.42,.86,.34));vec3 base=vColor*uColor;
float grain=noise(vWorld.xz*14.+vWorld.y*3.)*.06+noise(vWorld.xz*2.)*.08;
base*=.92+grain;
if(uKind==5.){float grass=noise(vWorld.xz*.8)*.35+noise(vWorld.xz*6.)*.10;base=mix(vec3(.26,.36,.11),vec3(.53,.58,.29),grass+.3);n=normalize(n+vec3(sin(vWorld.x*43.)*.05,0.,cos(vWorld.z*39.)*.05));}
float diff=max(dot(n,light),0.);float hemi=.40+.18*max(n.y,0.);float shade=uKind==2.||uKind==4.||uKind==6.?1.:shadow();vec3 color=base*(hemi+diff*.67*shade);
vec3 eye=normalize(uEye-vWorld);float spec=pow(max(dot(n,normalize(light+eye)),0.),38.);
color+=vec3(.98,.92,.7)*spec*.12;
if(uKind==2.){float caustic=pow(max(0.,sin(vWorld.x*2.5+sin(vWorld.z*1.4+uTime)*2.)*sin(vWorld.z*2.2+uTime*.8)),5.);color+=vec3(.1,.2,.16)*caustic;}
if(uKind==4.){n=normalize(vec3(sin(vWorld.x*.8+uTime)*.08,1.,cos(vWorld.z*.7+uTime*.8)*.08));float fres=pow(1.-max(dot(eye,n),0.),3.);color=mix(base,vec3(.76,.94,.92),fres*.7);color+=pow(max(dot(n,normalize(light+eye)),0.),120.)*.9;}
if(uKind==3.)color=base;
if(uKind==6.){vec3 direction=normalize(vWorld-uEye);color=mix(vec3(.85,.92,.82),vec3(.37,.67,.86),max(0.,direction.y));float sun=pow(max(0.,dot(direction,light)),600.);float cloud=smoothstep(.56,.76,noise(direction.xz*8.+uTime*.002))*.45*smoothstep(.10,.4,direction.y);color=mix(color,vec3(.99,.98,.9),cloud);color+=vec3(1.,.88,.53)*sun;gl_FragColor=vec4(color,1.);return;}
float fog=1.-exp(-length(uEye-vWorld)*uFogDensity);color=mix(color,uFog,clamp(fog,0.,.98));gl_FragColor=vec4(pow(max(color,vec3(0.)),vec3(.88)),uAlpha);}`;
export class Renderer {
 constructor(canvas){this.canvas=canvas;const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw Error('Este juego necesita WebGL. Activa la aceleración gráfica del navegador.');this.gl=gl;
  const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('No se pudo iniciar el motor gráfico');return s};const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error('No se pudo enlazar el motor gráfico');gl.useProgram(p);this.program=p;this.loc={};for(const name of ['uModel','uVP','uNormal','uTime','uKind','uColor','uEye','uFog','uFogDensity','uAlpha','uLightVP','uShadowMap'])this.loc[name]=gl.getUniformLocation(p,name);this.attrs=['aPosition','aNormal','aColor'].map(n=>gl.getAttribLocation(p,n));gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.resize();
    const shadowProgram=gl.createProgram();gl.attachShader(shadowProgram,compile(gl.VERTEX_SHADER,'attribute vec3 aPosition;uniform mat4 uModel,uVP;void main(){gl_Position=uVP*uModel*vec4(aPosition,1.);}'));gl.attachShader(shadowProgram,compile(gl.FRAGMENT_SHADER,'precision highp float;void main(){vec4 p=fract(gl_FragCoord.z*vec4(1.,255.,65025.,16581375.));p-=p.yzww*vec4(1./255.,1./255.,1./255.,0.);gl_FragColor=p;}'));gl.linkProgram(shadowProgram);this.shadowProgram=shadowProgram;this.shadowLoc={uModel:gl.getUniformLocation(shadowProgram,'uModel'),uVP:gl.getUniformLocation(shadowProgram,'uVP')};this.shadowAttr=gl.getAttribLocation(shadowProgram,'aPosition');this.shadowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadowTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1536,1536,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.shadowBuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowBuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.shadowTexture,0);const depth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,1536,1536);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,depth);gl.bindFramebuffer(gl.FRAMEBUFFER,null);const ortho=new Float32Array([1/36,0,0,0,0,1/36,0,0,0,0,-2/110,0,0,0,-1,1]);this.lightVP=multiply(ortho,view([-27,55,22],[0,0,0]));
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true});
 }
 resize(){const r=this.canvas.parentElement.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.8);this.canvas.width=Math.max(320,Math.round(r.width*d));this.canvas.height=Math.max(200,Math.round(r.height*d));this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
 mesh(data){const g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);return {b,count:data.length/9}}
 shadowBegin(){const g=this.gl;this.depthPass=true;g.bindFramebuffer(g.FRAMEBUFFER,this.shadowBuffer);g.viewport(0,0,1536,1536);g.disable(g.BLEND);g.clearColor(1,1,1,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.shadowProgram);g.uniformMatrix4fv(this.shadowLoc.uVP,false,this.lightVP)} shadowEnd(){const g=this.gl;this.depthPass=false;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.enable(g.BLEND)} begin(eye,target,time,underwater=false){if(this.lost)throw Error('Se perdió el contexto gráfico. Recarga para continuar tu partida guardada.');const g=this.gl;this.fog=underwater?[.18,.65,.72]:[.73,.86,.8];g.clearColor(...this.fog,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.program);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.shadowTexture);g.uniform1i(this.loc.uShadowMap,0);g.uniformMatrix4fv(this.loc.uLightVP,false,this.lightVP);g.uniformMatrix4fv(this.loc.uVP,false,multiply(perspective(this.canvas.width/this.canvas.height),view(eye,target)));g.uniform3fv(this.loc.uEye,eye);g.uniform3fv(this.loc.uFog,this.fog);g.uniform1f(this.loc.uFogDensity,underwater?.028:.008);g.uniform1f(this.loc.uTime,time);}
 draw(mesh,p=[0,0,0],s=[1,1,1],color=[1,1,1],r=[0,0,0],kind=0,alpha=1){const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,mesh.b);if(this.depthPass){g.enableVertexAttribArray(this.shadowAttr);g.vertexAttribPointer(this.shadowAttr,3,g.FLOAT,false,36,0);g.uniformMatrix4fv(this.shadowLoc.uModel,false,model(p,s,r));g.drawArrays(g.TRIANGLES,0,mesh.count);return}this.attrs.forEach((a,i)=>{g.enableVertexAttribArray(a);g.vertexAttribPointer(a,3,g.FLOAT,false,36,i*12)});g.uniformMatrix4fv(this.loc.uModel,false,model(p,s,r));const nm=model([0,0,0],s.map(v=>1/v),r);g.uniformMatrix3fv(this.loc.uNormal,false,new Float32Array([nm[0],nm[1],nm[2],nm[4],nm[5],nm[6],nm[8],nm[9],nm[10]]));g.uniform3fv(this.loc.uColor,color);g.uniform1f(this.loc.uKind,kind);g.uniform1f(this.loc.uAlpha,alpha);g.drawArrays(g.TRIANGLES,0,mesh.count)}
}
export function vertexData(p,n,c=[1,1,1]){return [...p,...n,...c]}
export function triangle(a,b,c,color=[1,1,1]){const n=V.norm(V.cross(V.sub(b,a),V.sub(c,a)));return [...vertexData(a,n,color),...vertexData(b,n,color),...vertexData(c,n,color)]}
export function sphere(lat=14,lon=20){const data=[];const point=(a,b)=>[Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];for(let i=0;i<lat;i++)for(let j=0;j<lon;j++){const a=i*Math.PI/lat,b=j*2*Math.PI/lon,da=Math.PI/lat,db=2*Math.PI/lon;for(const v of [point(a,b),point(a+da,b),point(a+da,b+db),point(a,b),point(a+da,b+db),point(a,b+db)])data.push(...vertexData(v,v))}return data}
export function cylinder(segments=12,taper=.7){const data=[];for(let i=0;i<segments;i++){const a=i*2*Math.PI/segments,b=(i+1)*2*Math.PI/segments;const p=[Math.cos(a),0,Math.sin(a)],q=[Math.cos(b),0,Math.sin(b)],r=[Math.cos(b)*taper,1,Math.sin(b)*taper],s=[Math.cos(a)*taper,1,Math.sin(a)*taper];data.push(...triangle(p,q,r),...triangle(p,r,s),...triangle([0,1,0],s,r))}return data}
export function box(){const data=[],v=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];for(const [a,b,c,d]of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])data.push(...triangle(v[a],v[b],v[c]),...triangle(v[a],v[c],v[d]));return data}
export function transform(data,p,s,r=[0,0,0],color=[1,1,1]){const m=model(p,s,r),n=model([0,0,0],s.map(v=>1/v),r),out=[];for(let i=0;i<data.length;i+=9){let v=data.slice(i,i+3),normal=data.slice(i+3,i+6);for(let k=0;k<3;k++)out.push(m[k]*v[0]+m[k+4]*v[1]+m[k+8]*v[2]+m[k+12]);out.push(...V.norm([0,1,2].map(k=>n[k]*normal[0]+n[k+4]*normal[1]+n[k+8]*normal[2])));out.push(...color.map((c,k)=>c*data[i+6+k]))}return out}
export const hash=(x,z=0)=>{const n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)};
