import {Sound} from './core.js';
import {Tetris,Buscaminas,Solitario} from './clasicos.js';
import {createPacman} from './pacman/engine.js';

const catalog=[
 {id:'pacman',name:'Pac-Man',tag:'ARCADE · 10 NIVELES',desc:'Un laberinto. Cuatro fantasmas. Ninguna vuelta igual.',help:'Flechas o WASD para moverte. Come las pastillas grandes para perseguir a los fantasmas. Completa diez niveles.',keys:[['←','ArrowLeft'],['↑','ArrowUp'],['↓','ArrowDown'],['→','ArrowRight']]},
 {id:'tetris',name:'Tetris',tag:'PUZLE · SIN LÍMITE',desc:'Encuentra el ritmo. Deja espacio para lo que viene.',help:'Flechas: mover y girar. Espacio: caída instantánea. C: reservar pieza. Z: giro inverso. La velocidad aumenta cada diez líneas.',keys:[['←','ArrowLeft'],['Girar ↻','ArrowUp'],['↓','ArrowDown'],['→','ArrowRight'],['Caer',' '],['Reservar','c']]},
 {id:'buscaminas',name:'Buscaminas',tag:'LÓGICA · 18 MINAS',desc:'A veces, el mejor movimiento es pensar un poco más.',help:'Toca para descubrir. Activa Bandera o usa clic derecho para marcar. Toca un número con sus banderas completas para abrir los vecinos. Primera apertura segura.',keys:[['⚑ Bandera','f']]},
 {id:'solitario',name:'Solitario',tag:'CARTAS · KLONDIKE',desc:'El pequeño placer de poner todo en su lugar.',help:'Toca la baraja para sacar una carta. Selecciona una carta o secuencia y su destino. Alterna colores en orden descendente; solo reyes en columnas vacías. As a rey por palo arriba.',keys:[['Auto a bases','a'],['Deshacer','u']]},
 {id:'selva',name:'DOON · Selva viva',tag:'AVENTURA · 3D',desc:'La luz atraviesa las hojas. Algo se mueve entre las ruinas.',help:'WASD: caminar. Flechas o arrastra: mirar. Espacio/clic: disparar. 1–3: armas. E: poder. Shift: correr. Recupera suministros y supera tres oleadas.',keys:[['←','a'],['↑','w'],['↓','s'],['→','d'],['Mirar ↶','ArrowLeft'],['Mirar ↷','ArrowRight'],['Disparar',' '],['Arma','q'],['Poder','e']]},
 {id:'sorpresa',name:'Una puerta inesperada',tag:'SORPRESA · 3D',desc:'Hay mundos que solo aparecen cuando te detienes a mirar.',help:'WASD o flechas: explorar. Arrastra para mirar. Espacio: ascender. C: descender. E: pulso explorador. Encuentra los diez tesoros antes de que se agote el oxígeno.',keys:[['←','a'],['↑','w'],['↓','s'],['→','d'],['Mirar ↶','ArrowLeft'],['Mirar ↷','ArrowRight'],['Subir',' '],['Bajar','c'],['Pulso','e']]}
];
const sound=new Sound(),rooms=[];let active=null,last=0;
const status=document.getElementById('session-status');
async function api(id,options={},records=false){if(options.method==='PUT'){const token=document.cookie.split(';').map(s=>s.trim()).find(s=>s.startsWith('pcs_csrf='));options.headers={...options.headers,'X-CSRF-Token':token?decodeURIComponent(token.slice(9)):''}}const r=await fetch(`/api/juegos?juego=${id}${records?'&action=records':''}`,{credentials:'same-origin',cache:'no-store',...options});if(!r.ok){const e=Error(r.status===401?'Inicia sesión para jugar y guardar tus partidas.':await r.text());e.status=r.status;throw e}return r.json()}
function message(room,text,error=false){room.message.textContent=text;room.message.classList.toggle('error',error)}
function overlay(room,title,subtitle,button='Continuar'){room.overlay.hidden=false;room.overlay.querySelector('strong').textContent=title;room.overlay.querySelector('span').textContent=subtitle;room.overlay.querySelector('button').textContent=button;}
function refreshHUD(room){room.hud.children[0].textContent=`${Number(room.game.score).toLocaleString('es-CO')} puntos`;room.hud.children[1].textContent=room.game.info;}
async function save(room){if(!room.game||!room.loaded)return;if(room.saving){room.saveAgain=true;return room.saving}message(room,'Guardando partida…');room.saving=(async()=>{try{do{room.saveAgain=false;const data=await api(room.item.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:room.version,puntaje:room.game.score,estado:room.game.save()})});room.version=data.version;await ranking(room)}while(room.saveAgain);message(room,`Guardado · ${new Date().toLocaleTimeString('es-CO')}`)}catch(e){message(room,e.message,true);if(e.status===409){pause(room,false);room.loaded=false;overlay(room,'Partida actualizada en otro equipo','Pulsa Cargar partida para recuperar la última versión.');room.overlay.querySelector('button').disabled=true}}finally{room.saving=null;room.saveAgain=false}})();return room.saving}
function pause(room,persist=true){if(!room?.game)return;room.running=false;room.game.pause();if(active===room)active=null;room.pause.textContent='▶ Continuar';overlay(room,room.game.over?(room.game.s?.won?'¡Lo conseguiste!':'Partida terminada'):'Pausa',room.game.over?'Tu puntaje queda en el registro. Empieza una nueva partida cuando quieras.':'Tu mundo puede esperar. Continúa cuando estés listo.');room.overlay.querySelector('button').hidden=room.game.over;if(persist)void save(room)}
async function play(room){if(!room.game||!room.loaded||room.game.over)return;if(active&&active!==room)pause(active);try{await sound.unlock();sound.effect("move")}catch{message(room,'El navegador no pudo activar el sonido. Puedes seguir jugando.',true)}room.game.active=true;room.game.keys={};active=room;room.running=true;room.overlay.hidden=true;room.pause.textContent='Ⅱ Pausar';room.canvas.focus({preventScroll:true});}
async function ranking(room){try{const {records}=await api(room.item.id,{},true);const top=room.card.querySelector('.record-top'),list=room.card.querySelector('.record-list');top.replaceChildren();list.replaceChildren();if(!records.length){const e=document.createElement('p');e.className='empty';e.textContent='Este récord todavía no tiene nombre. Puede ser el tuyo.';top.append(e);return}const first=records[0];for(const [cls,text]of [['record-crown','♛'],['record-name',first.nombre],['record-score',Number(first.puntaje).toLocaleString('es-CO')],['record-date',new Date(first.fecha).toLocaleString('es-CO')]]){const el=document.createElement('div');el.className=cls;el.textContent=text;top.append(el)}records.slice(1,6).forEach((record,i)=>{const li=document.createElement('li'),n=document.createElement('span'),p=document.createElement('b');n.textContent=`${i+2}. ${record.nombre}`;p.textContent=Number(record.puntaje).toLocaleString('es-CO');li.title=new Date(record.fecha).toLocaleString('es-CO');li.append(n,p);list.append(li)})}catch(e){room.card.querySelector('.record-top').textContent=e.message}}
async function load(room,explicit=false){try{if(explicit&&room.running)pause(room,false);if(room.saving)await room.saving;const data=await api(room.item.id);room.version=data.partida.version;room.loaded=true;room.overlay.querySelector('button').disabled=false;room.overlay.querySelector('button').hidden=false;if(data.partida.estado){await room.game.load(data.partida.estado);overlay(room,'Tu partida te espera','Retoma exactamente donde te quedaste.','Continuar partida');message(room,`Último guardado: ${new Date(data.partida.actualizado_en).toLocaleString('es-CO')}`)}else {if(explicit)await room.game.reset();overlay(room,'¿Una partida?','Pulsa Jugar para activar controles y sonido.','Jugar');message(room,'Todavía no tienes una partida guardada.')}room.game.render();refreshHUD(room);status.textContent=`Sala de ${data.nombre} · Partidas privadas, récords compartidos.`}catch(e){room.loaded=false;overlay(room,'Tu sesión es necesaria',e.message,'Reintentar');message(room,e.message,true);if(e.status===401){status.replaceChildren();const link=document.createElement('a');link.href='/login.html';link.textContent='Iniciar sesión para entrar a Juegos';status.append(link)}}}
for(const [index,item]of catalog.entries()){
 const card=document.createElement('section');card.id=item.id;card.className='game-card';card.innerHTML=`<div class="card-head"><span class="game-number">0${index+1}</span><div class="title-group"><h2>${item.name}</h2><p>${item.desc}</p></div><span class="tag">${item.tag}</span></div><div class="card-body"><div class="game-main"><div class="stage" data-game="${item.id}"><canvas tabindex="0" aria-label="${item.name}, área de juego"></canvas><div class="hud"><span>0 puntos</span><span></span></div><div class="overlay"><strong>Preparando juego…</strong><span></span><button type="button" disabled>Jugar</button></div></div><div class="game-actions"><button data-action="pause">▶ Jugar</button><button data-action="save">Guardar</button><button data-action="load">Cargar partida</button><button data-action="new">Nueva</button><button data-action="sound" aria-pressed="true">♫ Sonido</button><button data-action="full">⛶ Pantalla completa</button></div><div class="controls" aria-label="Controles táctiles de ${item.name}"></div><p class="help">${item.help}</p><p class="save-status" role="status"></p></div><aside class="ranking"><h3>RÉCORD ENTRE EMPRESAS</h3><div class="record-top"><p class="empty">Cargando clasificación…</p></div><ol class="record-list"></ol><button class="refresh-rank">Actualizar clasificación</button></aside></div>`;
 document.getElementById('games').append(card);const room={item,card,canvas:card.querySelector('canvas'),overlay:card.querySelector('.overlay'),hud:card.querySelector('.hud'),message:card.querySelector('.save-status'),pause:card.querySelector('[data-action=pause]'),running:false,loaded:false,version:0};rooms.push(room);
 room.overlay.querySelector('button').onclick=()=>room.loaded?play(room):load(room);
 card.querySelector('.refresh-rank').onclick=()=>ranking(room);
 card.querySelector('.game-actions').addEventListener('click',async e=>{const action=e.target.dataset.action;if(!action)return;try{if(action==='pause'){if(room.running)pause(room);else await play(room)}if(action==='save'){pause(room,false);await save(room)}if(action==='load'){if(confirm('¿Cargar la última partida guardada? Los avances sin guardar se reemplazarán.'))await load(room,true)}if(action==='new'&&room.game&&room.loaded){if(!confirm('¿Empezar una partida nueva? Se reemplazará tu guardado; tu récord se conserva.'))return;pause(room,false);if(room.saving)await room.saving;await room.game.reset();room.overlay.querySelector('button').hidden=false;await save(room);await play(room)}if(action==='sound'){sound.enabled=!sound.enabled;for(const r of rooms){const b=r.card.querySelector('[data-action=sound]');b.textContent=sound.enabled?'♫ Sonido':'♪ Silencio';b.setAttribute('aria-pressed',String(sound.enabled))}if(sound.enabled){await sound.unlock();sound.effect('score')}}if(action==='full'){if(document.fullscreenElement)await document.exitFullscreen();else if(card.requestFullscreen)await card.requestFullscreen();else message(room,'Este navegador no admite pantalla completa. Gira el celular para ampliar el juego.',true)}}catch(err){message(room,err.message,true)}});
 for(const [label,key]of item.keys){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',label);let repeat;b.addEventListener('pointerdown',e=>{e.preventDefault();if(!room.running)return;b.setPointerCapture(e.pointerId);room.game.key(key,true);b.classList.add('pressed');if(item.id==='tetris'&&['ArrowLeft','ArrowRight','ArrowDown'].includes(key))repeat=setInterval(()=>room.game.key(key,true),130);refreshHUD(room)});const release=()=>{clearInterval(repeat);room.game?.key(key,false);b.classList.remove('pressed')};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;card.querySelector('.controls').append(b)}
 room.canvas.addEventListener('contextmenu',e=>e.preventDefault());let pointer=null;
 room.canvas.addEventListener('pointerdown',e=>{if(!room.running)return;room.canvas.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,id:e.pointerId};if(room.game.click){room.game.click(room.game.point(e),e.button===2);refreshHUD(room)}else if(item.id==='selva'&&e.pointerType==='mouse'){room.game.key(' ',true)}});
 room.canvas.addEventListener('pointermove',e=>{if(!room.running||!pointer)return;if(room.game.look)room.game.look((e.clientX-pointer.x)*.006,(e.clientY-pointer.y)*.004);pointer.x=e.clientX;pointer.y=e.clientY});
 const releasePointer=()=>{pointer=null;room.game?.key(' ',false)};room.canvas.onpointerup=releasePointer;room.canvas.onpointercancel=releasePointer;
}
document.addEventListener('keydown',e=>{if(!active||e.target.tagName==='BUTTON')return;if(e.key==='Escape'||e.key.toLowerCase()==='p'){pause(active);return}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','w','a','s','d','e','q','c','x','z','u','f','1','2','3','Shift'].includes(e.key)){e.preventDefault();if(!e.repeat||active.item.id==='tetris')active.game.key(e.key,true)}});
document.addEventListener('keyup',e=>active?.game.key(e.key,false));document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause(active)});window.addEventListener('blur',()=>{if(active)pause(active)});
window.addEventListener('beforeunload',e=>{if(active){e.preventDefault();e.returnValue=''}});
setInterval(()=>{if(active)void save(active)},20000);
function tick(now){const dt=Math.min(.05,(now-last)/1000||.016);last=now;if(active?.running){const room=active;try{room.game.update(dt);refreshHUD(room);if(room.game.over){sound.effect(room.game.s?.won?'win':'lose');pause(room)}}catch(e){pause(room,false);message(room,'El juego se detuvo. Carga tu última partida para recuperar el estado.',true);console.error(e)}}requestAnimationFrame(tick)}requestAnimationFrame(tick);
for(const room of rooms){try{if(room.item.id==='pacman'){room.canvas.width=540;room.canvas.height=390;room.game=await createPacman(room.canvas,sound)}else if(room.item.id==='tetris')room.game=new Tetris(room.canvas,sound);else if(room.item.id==='buscaminas')room.game=new Buscaminas(room.canvas,sound);else if(room.item.id==='solitario')room.game=new Solitario(room.canvas,sound);else {const {WorldGame}=await import('./mundos.js');room.game=new WorldGame(room.canvas,sound,room.item.id)}room.game.render();await load(room);void ranking(room)}catch(e){message(room,e.message,true);overlay(room,'No se pudo preparar el juego',e.message);room.overlay.querySelector('button').hidden=true}}
function fit(room){if(!room.game)return;if(['selva','sorpresa'].includes(room.item.id)){room.game.resize();return}const canvas=room.canvas;if(document.fullscreenElement===room.card){const bounds=canvas.parentElement.getBoundingClientRect(),scale=Math.min(bounds.width/canvas.width,bounds.height/canvas.height);canvas.style.width=(canvas.width*scale)+'px';canvas.style.height=(canvas.height*scale)+'px'}else{canvas.style.width='100%';canvas.style.height='auto'}room.game.render()}
window.addEventListener('resize',()=>rooms.forEach(fit));document.addEventListener('fullscreenchange',()=>requestAnimationFrame(()=>rooms.forEach(fit)));
