import * as THREE from 'three';
import {BaseGame,copy} from '../core.js';
import {loadAssets} from './assets.js';
import {buildCity} from './city.js';
import {buildInterior} from './interiors.js';
import {LANDMARKS,MISSIONS,createState,nearestPlace} from './world-data.js';
import {clamp,distance,moveBody,gravity,angleTowards,createNavigation,findPath,pedestrianSteering} from './simulation.js';

export class SpringfieldGame extends BaseGame {
 static async create(canvas,sound){const assets=await loadAssets();return new SpringfieldGame(canvas,sound,assets)}
 constructor(canvas,sound,assets){
  super(canvas,sound,'simsong');this.assets=assets;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#bfdfed');this.scene.fog=new THREE.Fog('#c1dce2',170,500);
  this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
  this.camera=new THREE.PerspectiveCamera(60,1,.08,550);this.scene.add(new THREE.HemisphereLight('#e3f6ff','#9d9166',1.9));const sun=new THREE.DirectionalLight('#fff1d5',2.3);sun.position.set(-60,110,70);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-55,right:55,top:55,bottom:-55,near:1,far:220});sun.shadow.bias=-.001;this.sun=sun;this.scene.add(sun,sun.target);
  this.city=buildCity(assets);this.scene.add(this.city.group);this.cameraBoxes=this.city.colliders.map(b=>new THREE.Box3(new THREE.Vector3(b.x,b.minY,b.z),new THREE.Vector3(b.x+b.w,b.maxY,b.z+b.d)));this.interiors={home:buildInterior('home',assets),moe:buildInterior('moe',assets)};for(const i of Object.values(this.interiors)){i.group.visible=false;this.scene.add(i.group)}
  this.player=assets.actor('skaterMaleA');this.scene.add(this.player.root);this.nav=createNavigation(this.city.colliders);this.freeNodes=[];this.nav.grid.forEach((v,i)=>{if(v)this.freeNodes.push(this.nav.world(i%this.nav.size,Math.floor(i/this.nav.size)))});
  this.people=Array.from({length:18},(_,i)=>{const p=this.freeNodes[(i*197+800)%this.freeNodes.length],actor=assets.actor(['skaterMaleA','skaterFemaleA','criminalMaleA'][i%3]);this.city.group.add(actor.root);return {...p,y:0,yaw:0,actor,path:[],wait:i*.3,behavior:'paseando'}});
  const stage=canvas.parentElement;this.location=document.createElement('div');this.location.className='world-location';this.prompt=document.createElement('div');this.prompt.className='world-prompt';this.radar=document.createElement('canvas');this.radar.width=180;this.radar.height=180;this.radar.className='world-radar';this.radar.setAttribute('aria-label','Mapa de Springfield sin ruta guiada');this.board=document.createElement('section');this.board.className='mission-board';this.board.hidden=true;this.notice=document.createElement('div');this.notice.className='world-notice';this.notice.hidden=true;stage.append(this.location,this.prompt,this.radar,this.board,this.notice);this.board.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')this.board.hidden=true});this.reset();this.resize();
 }
 get info(){return this.s.driving>=0?`${Math.round(Math.abs(this.s.carSpeed)*3.6)} km/h`:`${this.s.completed.length}/${MISSIONS.length} misiones · ♥ ${this.s.health}`}
 reset(){this.s=createState();this.keys={};this.jump=false;this.board.hidden=true;this.city.cars.forEach((c,i)=>{c.x=i===0?-65:[-112,-40,32,104][i%4]+2.6;c.z=i===0?101:65-i*19;c.yaw=i===0?Math.PI/2:0;c.speed=0});this.syncScene();this.render()}
 save(){this.s.carStates=this.city.cars.map(c=>({x:c.x,z:c.z,yaw:c.yaw,speed:c.speed}));return super.save()}
 async load(p){
  if(p?.schema!==1||p.game!=='simsong'||p.data?.worldVersion!==1)throw Error('Esta partida pertenece a otra versión de Springfield.');const s=p.data;
  for(const key of ['x','y','z','yaw','cameraYaw','cameraPitch','score','time'])if(!Number.isFinite(s[key]))throw Error('La partida contiene una posición inválida.');
  if(Math.hypot(s.x,s.z)>198||s.y<0||s.y>170||!Array.isArray(s.visited)||!Array.isArray(s.completed)||!Number.isInteger(s.driving)||s.driving < -1||s.driving>=this.city.cars.length||![null,'home','moe'].includes(s.interior))throw Error('La partida no es compatible.');
  this.s={...createState(),...copy(s),vy:0};this.s.visited=s.visited.filter(id=>[...LANDMARKS.map(p=>p.id),'inside-home','inside-moe'].includes(id));this.s.completed=s.completed.filter(id=>MISSIONS.some(m=>m.id===id));this.s.carSpeed=clamp(Number(s.carSpeed)||0,-8,22);
  if(Array.isArray(s.carStates))s.carStates.slice(0,this.city.cars.length).forEach((saved,i)=>{if([saved.x,saved.z,saved.yaw,saved.speed].every(Number.isFinite)&&Math.hypot(saved.x,saved.z)<196)Object.assign(this.city.cars[i],{...saved,y:0,speed:clamp(saved.speed,-8,22)})});this.keys={};this.syncScene();this.render();
 }
 syncScene(){this.city.group.visible=!this.s.interior;for(const [id,i]of Object.entries(this.interiors))i.group.visible=id===this.s.interior;this.scene.fog=this.s.interior?null:new THREE.Fog('#c1dce2',170,500)}
 look(dx,dy){this.s.cameraYaw-=dx;this.s.cameraPitch=clamp(this.s.cameraPitch+dy,-.35,1.05)}
 action(key){if(key===' ')this.jump=true;if(key==='e')this.interact();if(key==='m'){this.board.hidden=!this.board.hidden;this.updateJournal()}}
 interact(){
  const s=this.s;
  if(s.interior){if(Math.hypot(s.x,s.z-8)<3.4&&s.y<1){const p=LANDMARKS.find(p=>p.id===s.interior);s.interior=null;s.x=p.door.x;s.z=p.door.z+2;s.y=0;s.cameraYaw=0;this.syncScene();this.sound.effect('card')}return}
  if(s.driving>=0){const car=this.city.cars[s.driving];for(const side of [-1,1]){const candidate={x:car.x+Math.cos(car.yaw)*side*2.2,z:car.z-Math.sin(car.yaw)*side*2.2,y:0};const test={x:car.x,z:car.z,y:0};if(!moveBody(test,candidate.x-test.x,candidate.z-test.z,this.city.colliders)){Object.assign(s,candidate);car.speed=0;s.driving=-1;s.carSpeed=0;return}}this.notify('Acerca el vehículo a un espacio libre para bajar.');return}
  const door=LANDMARKS.find(p=>p.door&&distance(s,p.door)<4.2);if(door){s.interior=door.id;Object.assign(s,this.interiors[door.id].spawn);s.vy=0;s.cameraYaw=Math.PI;s.cameraPitch=0;this.visit('inside-'+door.id);this.syncScene();this.sound.effect('card');return}
  const index=this.city.cars.findIndex(c=>distance(s,c)<4.2&&Math.abs(c.speed)<2);if(index>=0){s.driving=index;s.carSpeed=0;this.city.cars[index].parked=true;s.cameraYaw=this.city.cars[index].yaw;this.sound.effect('power')}
 }
 notify(text){this.notice.textContent=text;this.notice.hidden=false;this.noticeTime=4}
 visit(id){if(this.s.visited.includes(id))return;this.s.visited.push(id);this.s.score+=50;const p=LANDMARKS.find(p=>p.id===id);this.notify(p?`Descubriste ${p.name}`:'Un nuevo interior descubierto');this.sound.effect('score');for(const m of MISSIONS)if(!this.s.completed.includes(m.id)&&m.targets.every(t=>this.s.visited.includes(t))){this.s.completed.push(m.id);this.s.score+=m.reward;this.notify(`Misión cumplida: ${m.title} · +${m.reward}`);this.sound.effect('win')}this.updateJournal()}
 updateJournal(){this.board.replaceChildren();const title=document.createElement('h3');title.textContent='Tu Springfield · exploración libre';this.board.append(title);for(const m of MISSIONS){const p=document.createElement('p');p.textContent=`${this.s.completed.includes(m.id)?'✓':'○'} ${m.title} — ${m.description} (${m.targets.filter(t=>this.s.visited.includes(t)).length}/${m.targets.length})`;this.board.append(p)}const end=document.createElement('p');end.textContent=this.s.completed.length===MISSIONS.length?'Has conocido la ciudad. Puedes seguir explorando libremente.':'Elige tu misión. No hay un orden ni un camino obligatorio.';const close=document.createElement('button');close.textContent='Volver a explorar';this.board.append(end,close)}
 update(dt){
  const s=this.s,k=this.keys;s.time+=dt;if(k.ArrowLeft)s.cameraYaw+=dt*1.7;if(k.ArrowRight)s.cameraYaw-=dt*1.7;if(k.ArrowUp)s.cameraPitch=clamp(s.cameraPitch-dt,-.35,1.05);if(k.ArrowDown)s.cameraPitch=clamp(s.cameraPitch+dt,-.35,1.05);
  const forward=(k.w?1:0)-(k.s?1:0),side=(k.d?1:0)-(k.a?1:0);
  if(s.driving>=0){const car=this.city.cars[s.driving];s.carSpeed=clamp(s.carSpeed+forward*dt*8,-7,22);s.carSpeed*=Math.pow(forward?.995:.94,dt*60);car.yaw-=side*dt*1.15*clamp(s.carSpeed/5,-1,1);const blocked=moveBody(car,Math.sin(car.yaw)*s.carSpeed*dt,Math.cos(car.yaw)*s.carSpeed*dt,this.city.colliders,1.5,196);if(blocked){s.carSpeed=0;this.sound.tone(80,.06,'triangle',.015)}car.speed=s.carSpeed;s.x=car.x;s.z=car.z;s.y=0;s.yaw=car.yaw;if(forward)s.cameraYaw=angleTowards(s.cameraYaw,car.yaw,dt*2);if(Math.floor(s.time*5)!==Math.floor((s.time-dt)*5))this.sound.tone(45+Math.abs(s.carSpeed)*3,.17,'triangle',.014);
  }else{
   const length=Math.hypot(forward,side)||1,speed=k.Shift?6:3.4,dx=(Math.sin(s.cameraYaw)*forward-Math.cos(s.cameraYaw)*side)/length*speed*dt,dz=(Math.cos(s.cameraYaw)*forward+Math.sin(s.cameraYaw)*side)/length*speed*dt;
   const interior=this.interiors[s.interior],boxes=interior?.colliders||this.city.colliders;moveBody(s,dx,dz,boxes,.36,s.interior?100:198);if(interior){s.x=clamp(s.x,-9.45,9.45);s.z=clamp(s.z,-8.45,8.65)}gravity(s,dt,interior?.floorAt(s)||0,this.jump);if(dx||dz)s.yaw=angleTowards(s.yaw,Math.atan2(dx,dz),dt*12);if((dx||dz)&&s.y<.1&&Math.floor(s.time*3)!==Math.floor((s.time-dt)*3))this.sound.tone(120,.045,'triangle',.018);
  }
  this.jump=false;if(!s.interior){this.updateTraffic(dt);this.updatePeople(dt);for(const p of LANDMARKS)if(distance(s,p)<Math.max(p.w,p.d)*.65+5)this.visit(p.id)}
  if(this.noticeTime>0){this.noticeTime-=dt;if(this.noticeTime<=0)this.notice.hidden=true}this.player.animate(s.y>.15?'jump':(forward||side)&&s.driving<0?'run':'idle',dt);this.render();
 }
 updateTraffic(dt){for(const [i,c]of this.city.cars.entries()){if(i===this.s.driving||c.parked)continue;const obstacle=distance(c,this.s)<8||this.people.some(p=>distance(c,p)<5)||this.city.cars.some(o=>o!==c&&distance(c,o)<6);c.speed+=( (obstacle?0:5)-c.speed)*Math.min(1,dt*3);const dx=Math.sin(c.yaw)*c.speed*dt,dz=Math.cos(c.yaw)*c.speed*dt;if(moveBody(c,dx,dz,this.city.colliders,1.3,180)||Math.abs(c.z)>160){c.yaw+=Math.PI;c.x+=Math.cos(c.yaw)*5.2;c.speed=0}}}
 updatePeople(dt){for(const p of this.people){p.wait-=dt;if(!p.path.length&&p.wait<=0){const target=this.freeNodes[Math.floor(Math.random()*this.freeNodes.length)];p.path=findPath(this.nav,p,target);p.wait=2+Math.random()*3}const target=p.path[0];let moving=false;if(target){p.behavior='paseando';const v=pedestrianSteering(p,target,this.people,this.city.cars);const blocked=moveBody(p,v.x*dt,v.z*dt,this.city.colliders,.4,182);if(blocked){p.path=[];p.wait=.7}else{moving=Math.hypot(v.x,v.z)>.15;p.yaw=angleTowards(p.yaw,Math.atan2(v.x,v.z),dt*5)}if(distance(p,target)<.65)p.path.shift()}p.actor.root.position.set(p.x,0,p.z);p.actor.root.rotation.y=p.yaw;p.actor.animate(moving?'run':'idle',dt*.65)}}
 resize(){const b=this.canvas.parentElement.getBoundingClientRect();if(!b.width||!b.height)return;this.renderer.setSize(b.width,b.height,false);this.canvas.style.width=b.width+'px';this.canvas.style.height=b.height+'px';this.camera.aspect=b.width/b.height;this.camera.updateProjectionMatrix();this.render()}
 render(){
  if(!this.renderer||!this.s)return;const s=this.s;this.player.root.position.set(s.x,s.y,s.z);this.player.root.rotation.y=s.yaw;this.player.root.visible=!s.interior&&s.driving<0;for(const c of this.city.cars){c.root.position.set(c.x,0,c.z);c.root.rotation.y=c.yaw}
  const target=new THREE.Vector3(s.x,s.y+(s.driving>=0?1.6:1.45),s.z),forward=new THREE.Vector3(Math.sin(s.cameraYaw)*Math.cos(s.cameraPitch),-Math.sin(s.cameraPitch),Math.cos(s.cameraYaw)*Math.cos(s.cameraPitch));
  if(s.interior){this.camera.position.copy(target);this.camera.lookAt(target.clone().add(forward))}else{let distance=s.driving>=0?8:5.5;const ray=new THREE.Ray(target,forward.clone().negate()),point=new THREE.Vector3();for(const b of this.cameraBoxes){if(ray.intersectBox(b,point)){const d=target.distanceTo(point);if(d>.1&&d<distance)distance=Math.max(.3,d-.2)}}this.camera.position.copy(target).addScaledVector(forward,-distance);this.camera.lookAt(target)}
  this.sun.position.set(s.x-60,110,s.z+70);this.sun.target.position.set(s.x,0,s.z);this.sun.target.updateMatrixWorld();this.location.textContent=s.interior?(s.interior==='home'?'Casa de Homero · interior':'Taberna de Moe · interior'):nearestPlace(s.x,s.z).name;
  this.prompt.textContent=s.interior?(Math.hypot(s.x,s.z-8)<3.4&&s.y<1?'E · Salir':'Arrastra para mirar · WASD caminar'):s.driving>=0?'E · Bajar del vehículo':LANDMARKS.some(p=>p.door&&distance(s,p.door)<4.2)?'E · Entrar':this.city.cars.some(c=>distance(s,c)<4.2&&Math.abs(c.speed)<2)?'E · Conducir':Math.hypot(s.x,s.z)>190?'La cúpula marca el límite de Springfield':'M · Misiones · Explora libremente';
  this.drawMap();this.renderer.render(this.scene,this.camera);
 }
 drawMap(){const ctx=this.radar.getContext('2d');ctx.clearRect(0,0,180,180);ctx.fillStyle='#e8edce';ctx.beginPath();ctx.arc(90,90,86,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(90,90,86,0,Math.PI*2);ctx.clip();ctx.strokeStyle='#a5b0a8';ctx.lineWidth=4;for(const v of [-112,-40,32,104]){const n=90+v*.43;ctx.beginPath();ctx.moveTo(n,0);ctx.lineTo(n,180);ctx.moveTo(0,n);ctx.lineTo(180,n);ctx.stroke()}for(const p of LANDMARKS){ctx.fillStyle=this.s.visited.includes(p.id)?'#4d8b75':'#b28c73';ctx.fillRect(90+(p.x-p.w/2)*.43,90+(p.z-p.d/2)*.43,p.w*.43,p.d*.43)}ctx.fillStyle='#7441c4';ctx.beginPath();const place=LANDMARKS.find(p=>p.id===this.s.interior)||this.s;ctx.arc(90+place.x*.43,90+place.z*.43,4,0,Math.PI*2);ctx.fill();ctx.restore()}
}



