import test from 'node:test';
import assert from 'node:assert/strict';
import {Tetris,Buscaminas,Solitario} from '../web/juegos/clasicos.js';
import {V,multiply,model} from '../web/juegos/render3d.js';
import {createPacman} from '../web/juegos/pacman/engine.js';
import {WorldGame} from '../web/juegos/mundos.js';
import fs from 'node:fs';
const context=new Proxy({}, {get:(t,k)=>t[k]??(()=>{}),set:(t,k,v)=>(t[k]=v,true)});
const canvas=()=>({width:0,height:0,getContext:()=>context});const sound={effect(){}};
test('Tetris clears four lines, advances level and survives save/load',async()=>{const game=new Tetris(canvas(),sound);game.s.board=Array.from({length:20},(_,y)=>Array.from({length:10},(_,x)=>y>=16&&x!==4?1:0));game.s.piece=[[2],[2],[2],[2]];game.s.x=4;game.s.y=16;game.s.lines=8;game.lock();assert.equal(game.s.lines,12);assert.equal(game.s.level,2);assert.equal(game.score,800);const next=new Tetris(canvas(),sound);await next.load(game.save());assert.deepEqual(next.s,game.s);next.action('c');const hold=next.s.hold;next.action('c');assert.equal(next.s.hold,hold);assert.equal(next.s.held,true)});
test('Tetris collision ends the game without accessing outside board',()=>{const g=new Tetris(canvas(),sound);g.s.board=Array.from({length:20},()=>Array(10).fill(1));g.spawn();assert.equal(g.over,true)});
test('Mines first reveal and neighbors are safe; flood, flags and victory',()=>{for(let n=0;n<25;n++){const g=new Buscaminas(canvas(),sound);g.click({x:52,y:54});assert.equal(g.s.mines.length,18);assert.ok(!g.s.mines.includes(0));assert.ok(g.neighbors(0).every(i=>!g.s.mines.includes(i)));g.s.flagMode=true;const i=g.s.mines[0],p={x:24+i%12*56+28,y:26+Math.floor(i/12)*56+28};g.click(p);assert.ok(g.s.flags.includes(i));g.s.flagMode=false;g.click(p);assert.equal(g.over,false);for(let i=0;i<120;i++)if(!g.s.mines.includes(i))g.click({x:24+i%12*56+28,y:26+Math.floor(i/12)*56+28});assert.equal(g.s.won,true);assert.equal(g.s.open.length,102)}});
test('Mines loses on a bomb after first move',()=>{const g=new Buscaminas(canvas(),sound);g.click({x:52,y:54});const i=g.s.mines[0];g.click({x:24+i%12*56+28,y:26+Math.floor(i/12)*56+28});assert.equal(g.over,true);assert.equal(g.s.won,false)});
test('Solitaire deck has 52 unique cards and permits only legal moves',()=>{const g=new Solitario(canvas(),sound);let cards=[...g.s.stock,...g.s.cols.flat()];assert.equal(new Set(cards.map(c=>`${c.suit}:${c.rank}`)).size,52);g.s.cols=[[{rank:13,suit:0,up:true}],[{rank:12,suit:1,up:true}],[],[],[],[],[]];g.selected={type:'col',col:1,index:0};assert.equal(g.move({type:'col',col:2}),false);assert.equal(g.move({type:'col',col:0}),true);assert.equal(g.s.cols[0].length,2);g.action('u');assert.equal(g.s.cols[0].length,1);assert.equal(g.s.cols[1].length,1);g.s.waste=[{rank:1,suit:2,up:true}];g.auto({type:'waste',index:0});assert.equal(g.s.foundation[2].length,1);assert.equal(g.score,100)});
test('Solitaire victory persists and undo does not duplicate cards',async()=>{const g=new Solitario(canvas(),sound);g.s.foundation=Array.from({length:4},(_,suit)=>Array.from({length:suit===3?12:13},(_,n)=>({rank:n+1,suit,up:true})));g.s.waste=[{rank:13,suit:3,up:true}];g.s.stock=[];g.s.cols=Array.from({length:7},()=>[]);g.auto({type:'waste',index:0});assert.equal(g.over,true);assert.equal(g.s.won,true);const fresh=new Solitario(canvas(),sound);await fresh.load(g.save());assert.equal(fresh.score,5200);assert.equal(fresh.s.won,true)});
test('3D camera basis and matrix composition preserve world translation',()=>{assert.deepEqual(V.cross([1,0,0],[0,1,0]),[0,0,1]);const result=multiply(model([3,4,5]),model([2,0,0]));assert.deepEqual([...result.slice(12,15)],[5,4,5]);assert.deepEqual(V.norm([0,0,2]),[0,0,1])});
function world(ocean){const g=Object.create(WorldGame.prototype);g.ocean=true;g.id='sorpresa';g.obstacles=[];g.render=()=>{};g.sound={effect(){},tone(){}};g.reset();return g}
test('Underwater collection, oxygen recovery and loss preserve progress',async()=>{const g=world(true);g.s.oxygen=100;g.s.y=8.4;g.update(1);assert.ok(g.s.oxygen>100);for(const t of g.s.treasures){g.s.x=t.x;g.s.z=t.z;g.s.y=g.height(t.x,t.z)+1;g.update(.01)}assert.equal(g.s.collected,10);assert.equal(g.s.won,true);const lost=world(true);lost.s.oxygen=.01;lost.update(.1);assert.equal(lost.over,true);assert.equal(lost.s.won,false);const saved=world(true);await saved.load(g.save());assert.equal(saved.s.collected,10)});
test('Pac-Man moves, scores, restores directions and advances levels',async t=>{const originals={document:globalThis.document,Image:globalThis.Image,Element:globalThis.Element,fetch:globalThis.fetch};t.after(()=>Object.assign(globalThis,originals));globalThis.Element=class {};globalThis.Image=class extends globalThis.Element{async decode(){}};globalThis.document={createElement:()=>({...canvas(),width:540,height:390})};const map=JSON.parse(fs.readFileSync(new URL('../web/juegos/pacman/map.json',import.meta.url),'utf8'));globalThis.fetch=async()=>({ok:true,json:async()=>map});const c={...canvas(),width:540,height:390};const g=await createPacman(c,sound);g.action('ArrowRight');for(let i=0;i<60;i++)g.update(.034);assert.ok(g.score>0);const saved=g.save();await g.load(saved);g.action('ArrowUp');for(let i=0;i<60;i++)g.update(.034);assert.ok(g.score>=saved.score);const next=g.save();next.data.game.pillCount=0;await g.load(next);g.update(.05);await new Promise(resolve=>setTimeout(resolve,0));assert.match(g.info,/Nivel 2/);await g.reset();assert.equal(g.score,0);assert.match(g.info,/3 vidas/)});
