import test from 'node:test';
import assert from 'node:assert/strict';
import {createState} from '../web/juegos/simsong/world-data.js';
import {hitEnemy,hurtPlayer,advanceDeath,finishInvasion,normalizeCombat,raySphere,wallDistance} from '../web/juegos/simsong/combat.js';
test('Aliens and UFOs require multiple hits and award each kill once',()=>{const s=createState(),alien=s.enemies[0],ufo=s.enemies[12];assert.equal(hitEnemy(s,alien),false);assert.equal(s.score,0);hitEnemy(s,alien);assert.equal(hitEnemy(s,alien),true);assert.equal(s.score,250);hitEnemy(s,alien);assert.equal(s.score,250);for(let i=0;i<9;i++)assert.equal(hitEnemy(s,ufo),false);assert.equal(hitEnemy(s,ufo),true);assert.equal(s.score,1250);});
test('Three lives include the full death animation before ending or respawning',()=>{const s=createState();for(let lives=2;lives>=0;lives--){s.invulnerable=0;assert.equal(hurtPlayer(s,100),true);assert.equal(s.lives,lives);assert.equal(hurtPlayer(s,100),false);assert.equal(advanceDeath(s,2),true);assert.equal(s.over,false);advanceDeath(s,2.1);if(lives){assert.equal(s.health,100);assert.equal(s.deathTime,0);assert.equal(s.over,false)}else assert.equal(s.over,true)}});
test('Old saves gain combat defaults and new saves retain damage, lives and camera',()=>{assert.equal(normalizeCombat({}).lives,3);const s=createState();s.lives=1;s.cameraMode=2;s.enemies[12].hp=60;s.projectiles=[{x:1,y:2,z:3,vx:4,vy:5,vz:6,ttl:2}];const loaded=normalizeCombat(JSON.parse(JSON.stringify(s)));assert.equal(loaded.enemies[12].hp,60);assert.equal(loaded.cameraMode,2);assert.equal(loaded.lives,1);assert.deepEqual(loaded.projectiles,s.projectiles);assert.equal(normalizeCombat({cameraMode:99,lives:-2}).lives,0)});
test('Walls occlude laser targets and projectiles use swept collision',()=>{const origin={x:0,y:1,z:0},dir={x:0,y:0,z:1},boxes=[{x:-2,z:5,w:4,d:1,minY:0,maxY:3}];assert.equal(wallDistance(origin,dir,boxes),5);assert.equal(raySphere(origin,dir,{x:0,y:1,z:10},1,5),null);assert.equal(raySphere(origin,dir,{x:0,y:1,z:4},1,20),3);assert.equal(wallDistance({x:5,y:1,z:0},dir,boxes,30),30)});
test('Final invasion bonus is awarded once and free exploration remains available',()=>{const s=createState();assert.equal(finishInvasion(s),false);s.enemies.forEach(e=>hitEnemy(s,e,1000));assert.equal(finishInvasion(s),true);assert.equal(s.score,8000);assert.equal(finishInvasion(s),false);assert.equal(s.score,8000);assert.equal(s.over,false)});
